Add `Guild.fetch_role()` method to support proper handling of role mentionable in slash command options
Pycord-Development/pycord pull request #1101
Opened 2022-03-01 20:04 UTC by krittick

## Summary

This adds a new method `Guild.fetch_role()` which allows `utils.get_or_fetch` to work with roles properly. Previously it did not work because there was only a `fetch_roles` method, not `fetch_role`.

This also fixes #906 by having the "mentionable" option type check for first a user, then a role if a user is not found. This required the addition of `Guild.fetch_fole()` to work properly.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-03-01 20:42 UTC, Dorukyum requested changes

2022-03-01 20:42 UTC, Dorukyum commented on discord/guild.py
> +        .. versionadded:: 1.3
I think you forgot to change this :)
```suggestion
        .. versionadded:: 2.0
```

2022-03-01 20:45 UTC, Dorukyum submitted a review, later dismissed

2022-03-04 13:37 UTC, zeffo reviewed
Perhaps the note should be changed to ```This method is an API call. For general usage, consider using :attr:`get_role` instead.```

2022-03-04 15:29 UTC, BobDotCom commented
I feel like making this a private method "_fetch_role" would be more correct (And add handling for that inside get_or_fetch). This currently doesn't reflect the api well and shouldn't really be a method we promote, as it's rather "fetch_roles_and_filter_for_one_role"

2022-03-04 15:30 UTC, BobDotCom requested changes
See my last comment

2022-03-04 15:32 UTC, krittick commented
> I feel like making this a private method "_fetch_role" would be more correct (And add handling for that inside get_or_fetch). This currently doesn't reflect the api well and shouldn't really be a method we promote, as it's rather "fetch_roles_and_filter_for_one_role"

Good point. I'll update with those changes and test it out. Setting to draft for now.

2022-03-10 22:16 UTC, krittick commented
This is ready for review now.

2022-03-11 13:24 UTC, Icebluewolf approved these changes
I downloaded this branch and It fixed the problem for me!

2022-03-11 13:46 UTC, Dorukyum approved these changes

2022-03-11 18:31 UTC, RGBCube approved these changes

2022-03-19 23:54 UTC, BobDotCom approved these changes

2022-03-19 23:54 UTC, merged