Implement application command permissions v2
Pycord-Development/pycord pull request #1183
Opened 2022-03-19 21:19 UTC by BobDotCom

## Summary

Implements the new permissions system.
Original PR: #1129 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-03-24 08:59 UTC, TurnrDev commented
Just to be clear, what will this PR bring? What are the new changes to the permissions system?

2022-03-24 11:08 UTC, Dorukyum commented
This allows bot devs server managers to choose permission requirements (such as "manage messages") for commands

2022-04-07 05:24 UTC, AmirAvram commented
Will permissions v2 deprecate the ability to allow specific user_ids for commands? or is it just not planned for next release?

2022-04-27 06:13 UTC, TurnrDev commented
Is this PR frozen? Is there anything I can do to contribute?

2022-04-27 07:21 UTC, Lulalaby commented
> Is this PR frozen? Is there anything I can do to contribute?

Bob is atm out of order and the permission thing is not yet public

2022-04-27 20:30 UTC, krittick commented
Perms v2 is now available to all servers as of today: https://github.com/discord/discord-api-docs/pull/4830/files

2022-04-27 21:20 UTC, plun1331 reviewed
I'll work on a PR to add the new stuff documented in the Discord API PR later today, if it's not already being worked on

2022-04-27 21:20 UTC, plun1331 commented on discord/bot.py
>          global_permissions: List = []
I assume this code can be removed now

2022-04-27 21:20 UTC, plun1331 commented on docs/api.rst
> -CommandPermission
New permission decorators should be documented

2022-04-27 21:36 UTC, krittick commented on discord/bot.py
>          global_permissions: List = []
Yup.

2022-04-27 21:37 UTC, krittick commented
> I'll work on a PR to add the new stuff documented in the Discord API PR later today, if it's not already being worked on

Sounds great, thank you! I just resolved merge conflicts as well.

2022-04-27 22:22 UTC, Lulalaby commented
That's Teamwork ❤️

2022-04-28 14:33 UTC, BobDotCom commented on discord/commands/core.py
> +            f"Locale '{locale}' is not a valid locale, " f"see {docs}/reference#locales for list of supported locales."
What happened here

2022-04-28 14:33 UTC, BobDotCom commented on discord/commands/core.py
> +            f"Locale '{locale}' is not a valid locale, " f"see {docs}/reference#locales for list of supported locales."
What happened here

2022-05-05 12:53 UTC, Lulalaby submitted a review, later dismissed

2022-05-05 13:27 UTC, TurnrDev requested changes

2022-05-05 13:27 UTC, TurnrDev commented on discord/commands/core.py
> +    if not isinstance(name, str): not re.match(r"^[\w-]{1,32}$", name):
```suggestion
    if not isinstance(name, str) or not re.match(r"^[\w-]{1,32}$", name):
```

2022-05-05 13:30 UTC, Lulalaby approved these changes

2022-05-05 13:40 UTC, TurnrDev commented on discord/commands/core.py
> +    Permissions = TypeVar("Permissions")
#1324

2022-05-05 14:50 UTC, Lulalaby submitted a review, later dismissed

2022-05-05 20:52 UTC, plun1331 commented
Pretty much done except for gateway events

2022-05-05 20:55 UTC, Lulalaby approved these changes

2022-05-05 21:22 UTC, krittick approved these changes

2022-05-05 21:22 UTC, Lulalaby commented
@krittick wanna resolve mr conflicts?

2022-05-05 21:23 UTC, krittick commented
> @krittick wanna resolve mr conflicts?

Working on it now.

2022-05-05 21:25 UTC, merged