Documentation Updates
Pycord-Development/pycord pull request #1193
Opened 2022-03-23 18:00 UTC by plun1331

## Summary

Changes and fixes a lot of stuff in the documentation.

Things I remember doing:
- Documented cogs
- Documented ApplicationCommand exceptions and moved extension errors to `discord` from `ext.commands`
- Fixed many typos
- Added guide to index
- Renamed migrating to migrating to v1 to make room for a potential v2 migration guide
- Redid half the sink docs
- Fixed warnings while building docs
- Fixed a lot of broken references
- Notes the message content intent requirement at the top of ext.commands documentation (could be moved?)

**You can see a preview at https://pycord-plun1331.readthedocs.io/en/latest/index.html**

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-03-27 19:57 UTC, ooliver1 requested changes

2022-03-27 19:57 UTC, ooliver1 commented on discord/sinks/core.py
> +        """
may i suggest using the [pep 257 convention](https://peps.python.org/pep-0257) of docstrings
```py
"""short

longer
description
"""
```

2022-03-27 19:57 UTC, ooliver1 commented on docs/api.rst
> +.. autofunction:: discord.commands.core.application_command
is this a decorator? you may want the `:decorator:` option from sphinxcontrib-trio

2022-03-27 19:57 UTC, ooliver1 commented on docs/conf.py
> +    "guide": "https://guide.pycord.dev/"
trailing commas make sense for VCS so git diffs are only one line long, like how it is right now

2022-03-27 19:58 UTC, ooliver1 commented
oh also id highly recommend using proper commit messages when contributing - or just any time you make a commit message
helps with seeing what each commit did and when

2022-03-27 20:14 UTC, plun1331 commented
Suggested changes have been applied

2022-04-01 16:43 UTC, Dorukyum approved these changes
Looks good to me, thank you

2022-04-01 17:11 UTC, Middledot approved these changes
lgtm

2022-04-01 19:11 UTC, krittick approved these changes

2022-04-01 19:11 UTC, merged