Remove voice client when bot disconnects
Pycord-Development/pycord pull request #1273
Opened 2022-04-17 15:46 UTC by Dorukyum

## Summary
Fixes #1049.

## Checklist
- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-04-17 16:24 UTC, krittick submitted a review, later dismissed

2022-04-17 16:40 UTC, Middledot requested changes
Voice state updates only get dispatched for the client, ignoring other users

2022-04-17 22:03 UTC, Lulalaby approved these changes

2022-04-18 01:25 UTC, Middledot approved these changes

2022-04-18 01:27 UTC, merged