Update ApplicationContext Documentation
Pycord-Development/pycord pull request #1452
Opened 2022-06-27 16:03 UTC by JustaSqu1d

## Summary

Simply just added missing documentation for ApplicationContext.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-06-28 21:48 UTC, plun1331 requested changes

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """Optional[:class:`.Guild`]: Returns the guild associated with this context's command. Shorthand for :attr:`.Interaction.Guild`.
```suggestion
        """Optional[:class:`.Guild`]: Returns the guild associated with this context's command. Shorthand for :attr:`.Interaction.guild`.
```

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """`int`: Returns the ID of the channel associated with this context's command. Shorthand for :attr:`.Interaction.channel.id`."""
pretty sure this should also have :class:
```suggestion
        """:class:`int`: Returns the ID of the channel associated with this context's command. Shorthand for :attr:`.Interaction.channel.id`."""
```

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """`int`: Returns the ID of the guild associated with this context's command. Shorthand for :attr:`.Interaction.Guild.id`."""
```suggestion
        """:class:`int`: Returns the ID of the guild associated with this context's command. Shorthand for :attr:`.Interaction.guild.id`."""
```

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """`str`: Returns the locale of the guild associated with this context's command. Shorthand for :attr:`.Interaction.Guild.locale`."""
```suggestion
        """:class:`str`: Returns the locale of the guild associated with this context's command. Shorthand for :attr:`.Interaction.guild_locale`."""
```

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """`str`: Returns the locale of the guild associated with this context's command. Shorthand for :attr:`.Interaction.locale`."""
```suggestion
        """:class:`str`: Returns the locale of the guild associated with this context's command. Shorthand for :attr:`.Interaction.locale`."""
```

2022-06-28 21:48 UTC, plun1331 commented on discord/commands/context.py
> +        """Optional[:class:`.VoiceProtocol`]: Returns the voice client associated with this context's command. Shorthand for :attr:`.Interaction.Guild.voice_client`, if applicable."""
```suggestion
        """Optional[:class:`.VoiceProtocol`]: Returns the voice client associated with this context's command. Shorthand for :attr:`.Interaction.guild.voice_client`, if applicable."""
```

2022-06-28 22:03 UTC, Lulalaby submitted a review, later dismissed

2022-07-02 10:33 UTC, Dorukyum commented on discord/commands/context.py
> +        """
```suggestion
        """Union[:class:`.abc.Messageable`]:
        Returns the channel associated with this context's command. Shorthand for :attr:`.Interaction.channel`."""
```

2022-07-02 10:35 UTC, Dorukyum requested changes

2022-07-02 10:35 UTC, Dorukyum commented on discord/commands/context.py
> +        """
```suggestion
        """Union[:class:`abc.GuildChannel`, :class:`PartialMessageable`, :class:`Thread`]:
        Returns the channel associated with this context's command. Shorthand for :attr:`.Interaction.channel`."""
```

2022-07-02 10:35 UTC, Dorukyum commented on discord/commands/context.py
> +        """
```suggestion
        """Optional[:class:`.Guild`]: Returns the guild associated with this context's command. Shorthand for :attr:`.Interaction.guild`."""
```

2022-07-02 10:36 UTC, Dorukyum approved these changes

2022-07-02 11:25 UTC, Lulalaby approved these changes
LGTM

2022-07-02 11:25 UTC, merged