Update the pull request template
Pycord-Development/pycord pull request #1456
Opened 2022-06-28 12:40 UTC by Dorukyum

## Summary
Updates the PR template. I used it here so you can preview it. Open for ideas.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have searched the open pull requests for duplicates.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why

## PR Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2022-06-28 12:41 UTC, Dorukyum commented
Idea 1: `I have searched the open pull requests for duplicates.` could be unindented and moven up.

2022-06-28 13:47 UTC, ArjunSharda requested changes

2022-06-28 13:47 UTC, ArjunSharda commented on .github/PULL_REQUEST_TEMPLATE.md
> +    - [ ] I have searched the open pull requests for duplicates.
```suggestion
- [ ] I have searched open pull requests for duplicates.
```

2022-06-28 22:08 UTC, Lulalaby approved these changes

2022-06-28 22:14 UTC, ArjunSharda approved these changes

2022-06-30 15:23 UTC, Lulalaby submitted a review, later dismissed

2022-06-30 15:29 UTC, Lulalaby commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have updated the documentation to reflect the changes.
Keep it like that

2022-06-30 15:38 UTC, ArjunSharda submitted a review, later dismissed

2022-07-01 15:36 UTC, Dorukyum commented
I think we should actually move "PR Information" above "Checklist" because it gives the main info about the pr and will affect the other checklist.

2022-07-01 15:36 UTC, Lulalaby commented
true!

2022-07-01 16:02 UTC, Lulalaby submitted a review, later dismissed

2022-07-03 19:16 UTC, ArjunSharda commented on .github/PULL_REQUEST_TEMPLATE.md
>  - [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)
```suggestion
[ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).
```

2022-07-03 19:30 UTC, Lulalaby commented on .github/PULL_REQUEST_TEMPLATE.md
>  - [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)
oh true

2022-07-03 19:30 UTC, Lulalaby approved these changes

2022-07-03 19:33 UTC, Middledot approved these changes

2022-07-03 19:33 UTC, merged