Add new example when command-error happened.
Pycord-Development/pycord pull request #1474
Opened 2022-07-07 01:09 UTC by peco2282

## Summary

Add new example.
How to catch errors in commands when they occur.

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2022-07-10 02:50 UTC, plun1331 requested changes

2022-07-10 02:50 UTC, plun1331 commented on examples/command_error.py
> +    print("-" * 40)
Consistency
```suggestion
    print("------")
```

2022-07-10 02:50 UTC, plun1331 commented on examples/command_error.py
> +)
We don't need this many imports, just `import discord` and `from discord.ext import commands` is sufficient and maintains consistency with the other examples.

2022-07-10 02:50 UTC, plun1331 commented on examples/command_error.py
> +        return await ctx.send("This channel is not thread!")
Consider making the command simpler (reduce the number of exceptions), maybe a simple 'is admin' command or a moderation command.

2022-07-31 06:59 UTC, EmreTech requested changes

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    await ctx.channel.archive()
The comments are not needed, the code is very self-explanatory

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    await ctx.message.add_reaction(negative_emoji)
This comment is also not necessary

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    # This error occurs `bot_has_permissions` decorator.
```suggestion
    # This error occurs via the`bot_has_permissions` decorator.
```

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    # This error occurs `guild_only` decorator.
```suggestion
    # This error occurs via the `guild_only` decorator.
```

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    # This error occurs `check(is_thread)` decorator.
```suggestion
    # This error occurs via the `check(is_thread)` decorator, when `is_thread` returns false.
```

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +    # Occurs when is_thread function returns false. (the channel is not a thread)
```suggestion
    
```
I would've merged this suggestion with the bottom one but GitHub seems to not be able to do that

2022-07-31 06:59 UTC, EmreTech commented on examples/command_error.py
> +def is_thread(ctx: commands.Context) -> bool:
I feel like it would be a little better if the `is_thread` function check was defined right before the command that uses it

2022-09-26 11:14 UTC, Dorukyum requested changes

2022-09-26 11:14 UTC, Dorukyum commented on examples/command_error.py
> +    intents=intents
```suggestion
    intents=intents,
```

2022-09-26 11:14 UTC, Dorukyum commented on examples/command_error.py
> +positive_emoji: str = "\U00002705"
Maybe switch these constants to SCREAMING_SNAKE_CASE?
Also the typehint is unnecessary.

2022-10-16 17:22 UTC, Lulalaby commented
stale

2022-10-16 17:22 UTC, closed without merging