feat(bot.py): fix type issues
Pycord-Development/pycord pull request #1534
Opened 2022-07-30 08:05 UTC by EmreTech

## Summary

This PR fixes the (many) type issues in `bot.py` and a few type issues in `commands/core.py`.
This PR also makes the code more efficient and readable with issues that aren't entirely type related.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.

2022-07-31 17:13 UTC, searchify7 submitted a review, later dismissed

2022-08-12 17:46 UTC, BobDotCom requested changes

2022-08-12 17:46 UTC, BobDotCom commented
Please resolve merge conflicts

2022-08-12 17:47 UTC, EmreTech commented on discord/bot.py
> +        raise NotImplementedError
But it makes a lot more sense if you think about it
The name NotImplementedError implies that the function/class hasn't been implemented yet.

2022-08-18 20:39 UTC, BobDotCom commented
Is this finished?

2022-08-18 23:29 UTC, EmreTech commented
> Is this finished?

Nope, hence why it's still marked as a draft

2022-08-25 01:51 UTC, EmreTech commented
This is now ready for review.

2022-08-25 02:33 UTC, Lulalaby approved these changes
GJ

2022-09-03 09:14 UTC, Dorukyum approved these changes
LGTM, thank you

2022-09-03 09:14 UTC, merged