Make `interaction.user` non-optional
Pycord-Development/pycord pull request #1647
Opened 2022-09-24 17:11 UTC by Dorukyum

## Summary
At least one of the `member` and `user` fields in the interaction payload will be present unless it's a PING interaction. This change prevents type issues from occuring almost everywhere `Interaction.user` or `ApplicationContext.user` is used without a type check.

This will be a breaking change in case this attribute is accessed in a PING handler (such a case isn't in the lib) even though it would always be `None`.

## Information
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist
- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2022-09-24 18:04 UTC, Lulalaby approved these changes
lgtm

2022-09-30 23:31 UTC, BobDotCom requested changes
Alternatively I feel it would be better to keep `Interaction.user` optional (since it is), and instead make `ApplicationContext.user` non-optional with a `type: ignore`.

2022-09-30 23:31 UTC, BobDotCom commented on discord/interactions.py
> +        The user or member that sent the interaction. Will not be present in PING interactions.
```suggestion
    user: Optional[Union[:class:`User`, :class:`Member`]]
        The user or member that sent the interaction. Will be `None` in PING interactions.
```

2022-09-30 23:31 UTC, BobDotCom commented on discord/interactions.py
>          self._permissions: int = 0
```suggestion
        self.user: Optional[Union[User, Member]] = None
        self._permissions: int = 0
```

2022-09-30 23:31 UTC, BobDotCom commented on discord/interactions.py
> +                    pass
```suggestion
        # TODO: there's a potential data loss here
        if self.guild_id:
            guild = self.guild or self._state._get_guild(self.guild_id) or Object(id=self.guild_id)
            try:
                member = data["member"]  # type: ignore
            except KeyError:
                pass
            else:
                self._permissions = int(member.get("permissions", 0))
                if not isinstance(guild, Object):
                    cache_flag = self._state.member_cache_flags.interaction
                    self.user = guild._get_and_update_member(member, int(member["user"]["id"]), cache_flag)
```

2022-09-30 23:31 UTC, BobDotCom commented on discord/interactions.py
> +                    pass
```suggestion
                    self.user = Member(state=self._state, data=member, guild=guild)
        else:
            try:
                self.user = User(state=self._state, data=data["user"])
            except KeyError:
                pass
```

2022-09-30 23:31 UTC, BobDotCom commented on discord/commands/context.py
>          return self.interaction.user
```suggestion
        return self.interaction.user  # type: ignore
```

2022-10-01 05:54 UTC, Dorukyum commented
> Alternatively I feel it would be better to keep `Interaction.user` optional (since it is), and instead make `ApplicationContext.user` non-optional with a `type: ignore`.

Why keep `Interaction.user` the same? Not to remove the tons of type errors that occur in components or `on_interaction`? If we're changing one attribute, I think we should change the other too here.

2022-10-01 14:03 UTC, BobDotCom commented
> > Alternatively I feel it would be better to keep `Interaction.user` optional (since it is), and instead make `ApplicationContext.user` non-optional with a `type: ignore`.
> 
> Why keep `Interaction.user` the same? Not to remove the tons of type errors that occur in components or `on_interaction`? If we're changing one attribute, I think we should change the other too here.

Because we should not make invalid type hints, which is what this would currently do. We can set it as optional and `type: ignore` when we know it will be present. Otherwise it defeats the purpose of having type hints, if they're wrong anyways.

2022-10-01 15:50 UTC, Dorukyum commented
> > > Alternatively I feel it would be better to keep `Interaction.user` optional (since it is), and instead make `ApplicationContext.user` non-optional with a `type: ignore`.
> 
> > 
> 
> > Why keep `Interaction.user` the same? Not to remove the tons of type errors that occur in components or `on_interaction`? If we're changing one attribute, I think we should change the other too here.
> 
> 
> 
> Because we should not make invalid type hints, which is what this would currently do. We can set it as optional and `type: ignore` when we know it will be present. Otherwise it defeats the purpose of having type hints, if they're wrong anyways.

It'll only be wrong internally when PONG-ing interactions, if done

2022-10-16 17:17 UTC, Lulalaby commented
ping pong

2022-10-25 03:53 UTC, EmreTech commented
> Alternatively I feel it would be better to keep `Interaction.user` optional (since it is), and instead make `ApplicationContext.user` non-optional with a `type: ignore`.

I do not agree with this approach. It's a way better idea to just change the type hints. It'll be better in the long run.
It would also be a fantastic idea to split interactions into different classes like Disnake did, but that's for another PR.

2022-10-25 04:59 UTC, BobDotCom commented
> I do not agree with this approach. It's a way better idea to just change the type hints. It'll be better in the long run.

Why? In the solution I proposed, `Interaction.user` is type-hinted to `Optional[User]` which granted in most cases is a bit loose as it's typically not `None`. However, we cannot say that it is never `None`, because sometimes it is. That being said, we *can* say that it is never `None` for app command interactions, hence why `ApplicationContext` would not have an optional typehint.

> It would also be a fantastic idea to split interactions into different classes like Disnake did, but that's for another PR.

That sounds like a potentially better approach. If we go this route, the best course of action may be closing this PR in favor of a new PR for the split-interaction approach.

2022-10-26 11:14 UTC, Dorukyum commented
Splitting interaction classes is a major change and will most likely be breaking. It might just as well create more type issues like the ones this pr aims to solve.

2022-11-18 17:27 UTC, Dorukyum commented
I've made changes after we decided to only make `ApplicationContext.user` non-optional and keep `Interaction.user` as-is.

2022-11-18 17:28 UTC, Lulalaby approved these changes

2022-11-18 17:33 UTC, BobDotCom approved these changes

2022-11-18 17:38 UTC, merged