feat(ext.bridge): add bridge_commands attribute
Pycord-Development/pycord pull request #1787
Opened 2022-11-17 23:28 UTC by Middledot

## Summary
Adds access to BridgeCommand access directly.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2022-11-18 14:55 UTC, BobDotCom requested changes
Please add a changelog entry

2022-11-19 14:49 UTC, BobDotCom commented on CHANGELOG.md
> +- Added `bridge_commands` attribute for access to bridge command objects.
```suggestion
- Added `bridge_commands` attribute to `ext.bridge.Bot` for access to bridge command objects.
```

2022-11-19 15:14 UTC, BobDotCom approved these changes

2022-11-19 15:32 UTC, Lulalaby approved these changes

2022-11-19 20:10 UTC, Middledot commented
auto-merges apparently don’t work because I can’t approve

2022-11-19 20:14 UTC, Lulalaby commented
you're the only one for this right?
@BobDotCom

2022-11-20 07:00 UTC, Dorukyum approved these changes

2022-11-20 07:01 UTC, merged