chore: Update Guild.features docs and literal
Pycord-Development/pycord pull request #1788
Opened 2022-11-18 00:08 UTC by NeloBlivion

## Summary

Primarily adds the new `APPLICATION_COMMAND_PERMISSIONS_V2` guild feature documentation ([as per this recent announcement](http://discord.com/developers/docs/change-log#upcoming-application-command-permission-changes)). Alongside it, both the `GuildFeatures` Literal and `Guild.features` docs were updated to include missing features.

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2022-11-18 02:16 UTC, Lulalaby submitted a review, later dismissed

2022-11-18 04:48 UTC, BobDotCom requested changes
Please add a changelog entry

2022-11-20 08:34 UTC, Lulalaby approved these changes

2022-11-22 13:52 UTC, Dorukyum approved these changes

2022-11-22 13:59 UTC, Lulalaby approved these changes

2022-11-22 13:59 UTC, merged