feat: Add cover parameter to create_scheduled_event
Pycord-Development/pycord pull request #1831
Opened 2022-12-18 10:57 UTC by Snawe

## Summary

The parameter `cover` was missing in the `create_scheduled_event()` function

## Information

- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2022-12-18 10:59 UTC, Snawe commented
during fixing this issue, I saw that the payload parameter is actually called `image` and not cover... Would it make sense to rename `cover` at the create and edit command to `image`? (But that would be a breaking change!)

2022-12-19 11:16 UTC, Dorukyum commented
> during fixing this issue, I saw that the payload parameter is actually called `image` and not cover... Would it make sense to rename `cover` at the create and edit command to `image`? (But that would be a breaking change!)

The API wrapper should reflect the API, meaning the parameter should be called `image`.

2022-12-19 12:23 UTC, Snawe commented
> > during fixing this issue, I saw that the payload parameter is actually called `image` and not cover... Would it make sense to rename `cover` at the create and edit command to `image`? (But that would be a breaking change!)
> 
> The API wrapper should reflect the API, meaning the parameter should be called `image`.

Ok. Will change that as well. Should I attach the commit to this PR? Or should I create a new PR since it is a breaking change?

2022-12-19 12:39 UTC, Lulalaby requested changes

2022-12-19 12:39 UTC, Lulalaby commented on discord/guild.py
> +        cover: bytes = MISSING,
```suggestion
        image: bytes = MISSING,
```

2022-12-19 12:39 UTC, Lulalaby commented on discord/guild.py
> +        cover: Optional[:class:`bytes`]
```suggestion
        image: Optional[:class:`bytes`]
```

2022-12-19 12:39 UTC, Lulalaby commented on discord/guild.py
> +        if cover is not MISSING:
```suggestion
        if image is not MISSING:
```

2022-12-19 12:39 UTC, Lulalaby commented on discord/guild.py
> +            payload["image"] = utils._bytes_to_base64_data(cover)
```suggestion
            payload["image"] = utils._bytes_to_base64_data(image)
```

2022-12-19 12:39 UTC, Lulalaby commented
It's not a breaking change

2022-12-19 12:52 UTC, Snawe commented
> It's not a breaking change

Why is it not a breaking change? You would need to change the paramter of `edit` [here](https://docs.pycord.dev/en/stable/api/models.html#discord.ScheduledEvent.edit) from `cover` to `image`. 
`edit` does already exist. Changing a parameter in an existing function is a breaking change, isn't it?

For `create` I am with you. Since the parameter is new there, it doesn't matter.

2022-12-19 14:12 UTC, Lulalaby commented
oh didn't knew we have it there alr

We'll target that in another pr.
But only on the next breaking release.
So don't worry about it, we add this to our todo.
You can create a issue tho for that, that would help us to keep track.

2022-12-19 14:13 UTC, Lulalaby approved these changes

2022-12-19 14:55 UTC, Snawe commented
Will create an issue and attach a PR to it with the breaking changes.

2023-01-05 17:12 UTC, BobDotCom submitted a review, later dismissed

2023-01-05 17:18 UTC, Lulalaby approved these changes

2023-01-05 17:22 UTC, merged