fix: SlashCommandGroup.walk_commands() error
Pycord-Development/pycord pull request #1838
Opened 2022-12-23 21:57 UTC by KrishnanS2006

## Summary

Stops `SlashCommandGroup.walk_commands()` from returning `SlashCommandGroup`s.

When `SlashCommandGroup`s have other `SlashCommandGroup`s as subcommands, they are also yielded in `SlashCommandGroup.walk_commands()`, even though only `SlashCommand`s should be yielded from `walk_commands()`.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.

2023-01-05 17:17 UTC, BobDotCom commented
I'm unsure about this one, are we sure that we only want it to return `SlashCommand` objects? 

cc. @Dorukyum

2023-01-05 22:59 UTC, KrishnanS2006 commented
> are we sure that we only want it to return `SlashCommand` objects?

Looking at the function's return type, it seemed so, which is why I made the pr... if we choose to keep existing functionality, we should at least change the typehint to reflect what the method does.

2023-02-14 18:46 UTC, Lulalaby approved these changes

2023-02-14 19:30 UTC, plun1331 requested changes

2023-02-14 19:30 UTC, plun1331 commented on discord/commands/core.py
> +            A nested slash command group from the group.
This should look like a typehint sorta
```suggestion
        :class:`.SlashCommand` | :class:`.SlashCommandGroup`
            A nested slash command or slash command group from the group.
```

2023-02-14 21:59 UTC, plun1331 approved these changes

2023-02-15 00:39 UTC, Lulalaby approved these changes

2023-02-15 00:39 UTC, merged

2023-02-15 00:42 UTC, JustaSqu1d commented
Bruh changelog entry tho.