Bridge Command Events
Pycord-Development/pycord pull request #1916
Opened 2023-02-10 16:39 UTC by Om1609

## Summary

Adds `on_bridge_command`, `on_bridge_command_completion` and `on_bridge_command_error`

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

2023-02-10 19:15 UTC, JustaSqu1d reviewed
Add a changelog entry.

2023-02-11 02:57 UTC, JustaSqu1d requested changes

2023-02-11 02:57 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added new events `on_bride_command`, `on_bridge_command_completion` and
Use an oxford comma and fix spelling.
```suggestion
- Added new events `on_bridge_command`, `on_bridge_command_completion`, and
```

2023-02-11 02:57 UTC, JustaSqu1d commented on docs/ext/bridge/api.rst
> +.. function:: discord.ext.bridge.on_command_error(ctx, error)
```suggestion
.. function:: discord.ext.bridge.on_bridge_command_error(ctx, error)
```

2023-02-11 02:57 UTC, JustaSqu1d commented on docs/ext/bridge/api.rst
> +.. function:: discord.ext.bridge.on_command(ctx)
```suggestion
.. function:: discord.ext.bridge.on_bridge_command(ctx)
```

2023-02-11 02:57 UTC, JustaSqu1d commented on docs/ext/bridge/api.rst
> +.. function:: discord.ext.bridge.on_command_completion(ctx)
```suggestion
.. function:: discord.ext.bridge.on_bridge_command_completion(ctx)
```

2023-02-11 02:57 UTC, JustaSqu1d commented on docs/ext/bridge/api.rst
> +    passed and the user input it correctly.
Subject-verb agreement
```suggestion
    passed and users input it correctly.
```

2023-02-11 02:57 UTC, JustaSqu1d commented on discord/ext/bridge/bot.py
> +                self.dispatch("bridge_command", ctx)
Should the text-based commands be called as well for consistency with application commands?

2023-02-11 16:37 UTC, JustaSqu1d approved these changes

2023-02-12 05:02 UTC, Lulalaby approved these changes

2023-02-12 07:14 UTC, Middledot approved these changes

2023-02-12 07:14 UTC, merged