Remove `reason` from being passed to AutoModRule
Pycord-Development/pycord pull request #1960
Opened 2023-03-06 15:55 UTC by Om1609

## Summary

`AutoModRule` does not accept a `reason` parameter. This raises an unexpected keyword argument error.
This PR fixes it.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2023-03-06 18:31 UTC, plun1331 requested changes

2023-03-06 18:31 UTC, plun1331 commented on discord/guild.py
>          data = await self._state.http.create_auto_moderation_rule(self.id, payload)
Move the reason param up here

```suggestion
        data = await self._state.http.create_auto_moderation_rule(self.id, payload, reason=reason)
```

2023-03-06 18:31 UTC, plun1331 commented
Please make a changelog entry as well

2023-03-07 14:23 UTC, plun1331 submitted a review, later dismissed

2023-03-09 16:45 UTC, BobDotCom requested changes

2023-03-09 16:49 UTC, BobDotCom approved these changes

2023-03-09 21:45 UTC, plun1331 approved these changes

2023-03-09 23:11 UTC, Lulalaby approved these changes

2023-03-09 23:11 UTC, merged