fix: webhook message editing on forums missing thread_id
Pycord-Development/pycord pull request #1981
Opened 2023-03-22 13:41 UTC by qoft

## Summary

Fix editing a webhook message if the thread is a forum post or if the thread is a private thread (no starter message)

Issue [here](https://github.com/Pycord-Development/pycord/issues/1979)

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-03-22 19:56 UTC, Lulalaby approved these changes

2023-03-22 19:57 UTC, Lulalaby requested changes

2023-03-22 19:57 UTC, Lulalaby commented on discord/webhook/async_.py
> +        elif isinstance(self.channel, ForumChannel):
The ci says ForumChannel can't be found

2023-03-26 16:54 UTC, qoft commented
Changes done

2023-04-02 22:54 UTC, qoft commented
bump

2023-04-02 23:29 UTC, Lulalaby commented
bump deez nuts

2023-04-02 23:39 UTC, qoft commented
changes were done already ☝😲

2023-04-03 00:12 UTC, Lulalaby commented
We check through prs if we have time.
No need to bump anything.

2023-04-03 06:03 UTC, plun1331 requested changes
Please add a changelog entry.

2023-04-18 01:45 UTC, Lulalaby commented
@qoft please address the requested changes

2023-04-18 19:05 UTC, Lulalaby approved these changes

2023-04-18 19:07 UTC, Lulalaby approved these changes

2023-04-18 19:21 UTC, ChickenDevs approved these changes

2023-04-18 19:21 UTC, merged