fix: add None support for ClientUser edit
Pycord-Development/pycord pull request #1994
Opened 2023-03-31 08:54 UTC by ItsRqtl

## Summary

Fixed `AttributeError: 'NoneType' object has no attribute 'startswith'` in `_bytes_to_base64_data` when using `None` to reset avatar.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-03-31 14:34 UTC, plun1331 requested changes
Please add a changelog.

2023-04-04 20:20 UTC, Lulalaby commented
conflicts

2023-04-05 00:35 UTC, Lulalaby approved these changes

2023-04-05 04:04 UTC, plun1331 approved these changes

2023-04-05 04:04 UTC, merged