Embed - add parameters
Pycord-Development/pycord pull request #1996
Opened 2023-04-02 11:45 UTC by davidhozic

## Summary
This PR adds parameters to ``discord.Embed`` as proposed in #1995.
It also adds 2 new classes to support the latter. The classes are: ``EmbedFooter`` and ``EmbedAuthor``

Example:
```py
import discord
import secret

embed = discord.Embed(
    author=discord.EmbedAuthor(
        name="Mr. President",
        icon_url="https://media.discordapp.net/attachments/1044657935608987808/1065995582654664724/svetlogo.png"
    ),
    footer=discord.EmbedFooter(text="This is a footer")
)

client = discord.Client()

@client.listen("on_ready")
async def start():
    channel = client.get_channel(1091835594243592293)
    await channel.send(embed=embed)
    await client.close()

client.run(secret.TOKEN)
```

which produces

![](https://media.discordapp.net/attachments/1091835594243592293/1092052048310186004/image.png)

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-04-02 14:21 UTC, JustaSqu1d requested changes
Also, note the change in their respective properties.

2023-04-02 14:21 UTC, JustaSqu1d commented on discord/embeds.py
> +        Url of the author icon image.
```suggestion
        The URL of the author icon image.
```

2023-04-02 14:21 UTC, JustaSqu1d commented on discord/embeds.py
> +        The url of the hyperlink created on the author name.
```suggestion
        The URL of the hyperlink created in the author's name.
```

2023-04-02 14:21 UTC, JustaSqu1d commented on discord/embeds.py
> +        Url of the footer icon image.
```suggestion
        The URL of the footer icon image.
```

2023-04-02 14:22 UTC, JustaSqu1d commented
Should we deprecate `set_author`, etc?

2023-04-02 14:33 UTC, davidhozic commented
> Should we deprecate `set_author`, etc?

I think that's a good idea yes

2023-04-02 14:46 UTC, davidhozic commented
> > Should we deprecate `set_author`, etc?
> 
> I think that's a good idea yes

On second thought, I'd leave it in, you still have the ``set_field_at`` and ``remove_field`` and other ``remove_`` methods available. 
Maybe you for example want to modify an embed from a received message and send it back, so these methods can be helpful.

2023-04-02 14:53 UTC, Lulalaby commented
> Should we deprecate `set_author`, etc?

No, not in every case you want to use the constructor.
And what if you want to modify it afterwards

2023-04-02 15:01 UTC, JustaSqu1d approved these changes

2023-04-02 16:26 UTC, Lulalaby submitted a review, later dismissed

2023-04-02 18:10 UTC, Nzii3 commented
I mean, I don't really see the point in this but, idk.

2023-04-02 18:11 UTC, Nzii3 approved these changes

2023-04-02 19:07 UTC, plun1331 reviewed
Ideally, embed.footer and embed.author should return their respective classes

2023-04-02 20:36 UTC, davidhozic commented
Not sure what ``proxy_icon_url`` is supposed to be, but I'll leave it in the constructor since it's needed for the ``@properties`` and it will give you an error anyways if you try to provide it since ``Embed`` internally calls the ``set_`` methods in it's constructor.

2023-04-03 03:41 UTC, plun1331 commented
> Not sure what `proxy_icon_url` is supposed to be, but I'll leave it in the constructor since it's needed for the `@properties` and it will give you an error anyways if you try to provide it manually since `Embed` internally calls the `set_` methods in it's constructor.

it's a value returned by discord that proxies the image through their cdn iirc

2023-04-03 11:07 UTC, Lulalaby commented
> it's a value returned by discord that proxies the image through their cdn iirc

That's correct

2023-04-03 15:30 UTC, JustaSqu1d approved these changes

2023-04-18 01:44 UTC, Lulalaby approved these changes

2023-04-18 01:54 UTC, merged