feat: voice message support
Pycord-Development/pycord pull request #2016
Opened 2023-04-14 22:35 UTC by Lulalaby

2023-04-14 23:57 UTC, JustaSqu1d requested changes

2023-04-14 23:57 UTC, JustaSqu1d commented on discord/permissions.py
> +        """:class:`bool`: Returns ``True`` if a umember can send voice messages.
```suggestion
        """:class:`bool`: Returns ``True`` if a member can send voice messages.
```

2023-04-15 00:00 UTC, Lulalaby commented on discord/permissions.py
> +        """:class:`bool`: Returns ``True`` if a umember can send voice messages.
Thanks!

2023-04-15 16:19 UTC, Dorukyum requested changes
The "versionadded"s should be 2.5

2023-04-15 16:20 UTC, Lulalaby commented on discord/permissions.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-15 16:20 UTC, Lulalaby commented on discord/message.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-15 16:20 UTC, Lulalaby commented on discord/message.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-15 16:20 UTC, Lulalaby commented on discord/flags.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-15 18:13 UTC, JustaSqu1d approved these changes

2023-04-18 15:42 UTC, BobDotCom submitted a review, later dismissed

2023-04-18 15:44 UTC, BobDotCom reviewed
test

2023-04-18 16:43 UTC, NeloBlivion approved these changes

2023-04-18 21:36 UTC, JustaSqu1d approved these changes

2023-04-18 22:08 UTC, Lulalaby commented
oops

2023-04-18 22:12 UTC, NeloBlivion submitted a review, later dismissed

2023-04-18 22:52 UTC, Dorukyum commented on discord/types/message.py
> +    duration_secs: NotRequired[float | None]
Why is this nullable while `waveform` isn't?

2023-04-24 18:35 UTC, Dorukyum requested changes

2023-04-25 17:11 UTC, ChickenDevs approved these changes

2023-04-25 17:11 UTC, merged