docs: added get_ command return statement why they may return NoneType
Pycord-Development/pycord pull request #2114
Opened 2023-06-12 03:18 UTC by Blue-Robin-Taken

## Summary

This pull request fixes the issue of the confusion on why get_ commands may return None. This message also points to fetch_ commands if get_ commands return None. It's not documented anywhere else that it retrieves from the cache, so it can be refered to in things like Stackoverflow posts and help channels.

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-06-12 03:24 UTC, JustaSqu1d requested changes
Perhaps use `..note` because this isn't part of the core functionality of the methods.

2023-06-12 04:11 UTC, JustaSqu1d requested changes

2023-06-12 04:11 UTC, JustaSqu1d commented on discord/client.py
> +                The :meth:`.client.fetch_channel` version of this command won't return ``None``, however it makes an API call.
Grammar
```suggestion
                The :meth:`.client.fetch_channel` version of this command won't return ``None``, however, it makes an API call.
```

2023-06-12 04:11 UTC, JustaSqu1d commented on discord/client.py
> +                The :meth:`.client.fetch_channel` version of this command won't return ``None``, however it makes an API call.
Across all of them btw

2023-06-12 20:55 UTC, JustaSqu1d requested changes

2023-06-13 03:51 UTC, Lulalaby commented
This is just a big mess..

Either we add a general info somewhere that get_x methods rely on cache, and fetch_x methods on rest, or we leave it out.
I feel like this is too much.
Plus the wording is bad and the info incorrect.

2023-06-13 03:51 UTC, closed without merging