Docs: added difference between get_ commands and fetch_ commands in FAQ
Pycord-Development/pycord pull request #2123
Opened 2023-06-14 23:01 UTC by Blue-Robin-Taken

Added the difference between get_ commands and fetch_ commands

## Summary

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-06-14 23:22 UTC, Lulalaby requested changes

2023-06-14 23:22 UTC, Lulalaby commented on docs/faq.rst
> +get_ commands retrieve from the cache and won't always raise if not found. fetch_ commands always make an API request and if not found, raise. Example: ::
Bad unprofessional wording

2023-06-15 00:09 UTC, Blue-Robin-Taken commented on docs/faq.rst
> +get_ commands retrieve from the cache and won't always raise if not found. fetch_ commands always make an API request and if not found, raise. Example: ::
What would be "professional"?

2023-06-26 05:42 UTC, Lulalaby submitted a review, later dismissed

2023-07-06 19:00 UTC, JustaSqu1d requested changes

2023-07-06 19:00 UTC, JustaSqu1d commented on docs/faq.rst
> +"Get" methods retrieve objects or data from the cache (general store of data) and can return ``None`` if not found (this doesn't raise an error). "Fetch" methods force an API request and will raise a
or
```suggestion
"Get" methods retrieve objects or data from the cache (general store of data) and can return ``None`` if not found. This doesn't raise an error. "Fetch" methods force an API request and will raise an error if not found. Example: ::
```

2023-07-06 19:00 UTC, JustaSqu1d commented on docs/faq.rst
> +"Get" methods retrieve objects or data from the cache (general store of data) and can return ``None`` if not found (this doesn't raise an error). "Fetch" methods force an API request and will raise a
I don't see why this is necessary.

2023-07-11 01:42 UTC, ChickenDevs submitted a review, later dismissed

2023-07-11 02:00 UTC, JustaSqu1d requested changes

2023-07-14 05:07 UTC, sus2790 commented
How about `get_or_fetch`?

2023-09-11 01:57 UTC, JustaSqu1d requested changes
> I think using a simpler example like bot.fetch_user vs bot.get_user would be easier to understand.

My previous review still applies.

2023-09-11 01:58 UTC, Lulalaby commented
I think this change leads to nowhere.
I'm still having the opinion that it's obvious.
We shouldn't deal with user stupidness.

2023-09-11 02:00 UTC, JustaSqu1d commented
> I think this change leads to nowhere. I'm still having the opinion that it's obvious. We shouldn't deal with user stupidness.

Saying that you need `members` intent to do this in another method instead of the function itself, for example, is anything, but obvious.

2023-09-11 02:01 UTC, Lulalaby commented
Then please create a solid pull request yourself with a correct faq about it or better document it in the docstring

2023-09-14 04:04 UTC, Blue-Robin-Taken commented
@Lulalaby What exactly do you want? 

> We shouldn't deal with user stupidness.

Please be professional. I know it's an online repo, but I'm a student. I'm still learning.

What would be a "solid" PR, and can't I edit and fix the PR here?

2023-09-14 04:06 UTC, Lulalaby commented
"user stupidness" wasn't meant as in your pr.
I meant it as in we shouldn't faq tf outta everything.

2023-09-14 15:11 UTC, JustaSqu1d requested changes
> > I think using a simpler example like bot.fetch_user vs bot.get_user would be easier to understand.
> 
> My previous review still applies.

You can't just re-request a review without acknowledging my previous one.

2023-09-14 15:45 UTC, plun1331 commented
my thoughts on this: i personally haven't seen this question frequently asked

2023-09-14 16:16 UTC, Lulalaby commented
Yeah exactly that and that's why I've closed it in the first place. But squid reopened it

2023-09-15 01:32 UTC, Blue-Robin-Taken commented
> > > I think using a simpler example like bot.fetch_user vs bot.get_user would be easier to understand.
> > 
> > 
> > My previous review still applies.
> 
> You can't just re-request a review without acknowledging my previous one.

I thought I did but I don't have much github experience... Sorry about that. I'll try to fix it

2023-09-15 02:00 UTC, Lulalaby commented
simple: no where

2023-09-15 03:52 UTC, plun1331 commented
> > my thoughts on this: i personally haven't seen this question frequently asked
> 
> Although it's not frequently asked, it's gotta be listed somewhere when it is asked. 
> Where else should it be listed then? @plun1331 

In the entire time I've been with pycord I've only observed it asked 3-5 times, and the answer is fairly simple to explain each time: get_x gets from cache, fetch_x fetches from discord

If we had to make an entry for every question asked about the library, this FAQ page would be extremely long

2023-09-15 03:58 UTC, Lulalaby commented
And so I'm closing it.

2023-09-15 03:58 UTC, closed without merging