Add `delete_auto_moderation_rule`
Pycord-Development/pycord pull request #2153
Opened 2023-06-27 12:52 UTC by llamaair

## Summary

Add a function to delete auto moderation rules either by name or id.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-06-27 16:44 UTC, NeloBlivion reviewed
Nowhere else in the library do we include a `name` kwarg for deletions (roles, emojis, guilds, channels etc.)... it shouldn't be included here either.
(We also already have [`AutoModRule.delete()`](https://docs.pycord.dev/en/master/api/models.html#discord.AutoModRule.delete), but having a method on guild is understandable to avoid an extra fetch.)

2023-06-28 06:56 UTC, llamaair commented
> Nowhere else in the library do we include a `name` kwarg for deletions (roles, emojis, guilds, channels etc.)... it shouldn't be included here either.

Ok, I'l remove th name kwarg 👍

2023-07-04 15:40 UTC, JustaSqu1d approved these changes

2023-07-04 16:43 UTC, Lulalaby requested changes

2023-07-04 16:43 UTC, Lulalaby commented on discord/guild.py
> +        name: str | None = None,
```suggestion
```

2023-07-04 16:43 UTC, Lulalaby commented on discord/guild.py
> +            The name of the auto moderation rule.
```suggestion
```

2023-07-04 16:43 UTC, Lulalaby commented on discord/guild.py
> +            If no auto moderation rule is found with the given name.
```suggestion
```

2023-07-04 16:43 UTC, Lulalaby commented on discord/guild.py
> +
```suggestion
```

2023-07-04 16:43 UTC, Lulalaby commented on discord/guild.py
> +        id: int | None = None,
```suggestion
        id: int,
```

2023-07-05 03:27 UTC, Lulalaby commented on discord/guild.py
> +        return
```suggestion
        return AutoModRule(state=self._state, data=data)
```

2023-07-05 03:27 UTC, Lulalaby commented on discord/guild.py
> +        id: Optional[int]
```suggestion
        id: int
```

2023-07-05 03:29 UTC, Lulalaby requested changes

2023-07-05 03:29 UTC, Lulalaby commented on discord/guild.py
> +        id: int
```suggestion
        id: :class:`int`
```

2023-07-05 03:29 UTC, Lulalaby commented on discord/guild.py
> +        reason: Optional[str]
```suggestion
        reason: Optional[:class:`str`]
```

2023-07-06 02:07 UTC, plun1331 requested changes

2023-07-06 02:07 UTC, plun1331 commented on CHANGELOG.md
> +  ([#2153]https://github.com/Pycord-Development/pycord/pull/2153)
Bad markdown
```suggestion
  ([#2153](https://github.com/Pycord-Development/pycord/pull/2153))
```

2023-07-06 02:07 UTC, plun1331 commented on discord/guild.py
> +        id: int,
`id` should be positional
```suggestion
        id: int,
        *,
```

2023-07-06 02:07 UTC, plun1331 commented on discord/guild.py
> +        return AutoModRule(state=self._state, data=data)
Deleting a rule does not return anything (status code 204)
https://discord.com/developers/docs/resources/auto-moderation#delete-auto-moderation-rule
Update the return typehint as well

2023-07-06 13:39 UTC, JustaSqu1d requested changes

2023-07-06 13:39 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added function `delete_auto_moderation_rule`.
```suggestion
- Added function `Guild.delete_auto_moderation_rule`.
```

2023-07-06 13:39 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added function `delete_auto_moderation_rule`.
The entry should also be appended to the bottom of the "Added" section, not the top.

2023-07-06 19:07 UTC, JustaSqu1d reviewed
Maybe add `AutoModRule.delete()` as well?

2023-08-29 01:32 UTC, Lulalaby approved these changes

2023-08-29 01:37 UTC, merged