fix: `ScheduledEvent.creator_id` returning incorrect type
Pycord-Development/pycord pull request #2162
Opened 2023-07-03 16:32 UTC by JustaSqu1d

## Summary

#2160

Technically, not incorrect, but consistent with the rest of the library.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2023-07-03 16:59 UTC, Dorukyum submitted a review, later dismissed

2023-07-03 16:59 UTC, Dorukyum commented on discord/scheduled_events.py
> +        self.creator_id = int(data.get("creator_id", None))
The API documentation states that this field is nullable:

> `creator_id` will be null and `creator` will not be included for events created before October 25th, 2021, when the concept of creator_id was introduced and tracked.

```suggestion
        self.creator_id: int | None = utils._get_as_snowflake(data, "creator_id")
```

Not tested.

2023-07-03 20:22 UTC, Lulalaby requested changes

2023-07-03 20:22 UTC, Lulalaby commented on CHANGELOG.md
> +- Fixed `fix: ScheduledEvent.creator_id` returning `str` instead of `int`.
```suggestion
- Fixed `ScheduledEvent.creator_id` returning `str` instead of `int`.
```

2023-07-04 06:20 UTC, Middledot approved these changes

2023-07-04 16:40 UTC, Lulalaby approved these changes

2023-07-04 16:40 UTC, merged

2023-07-08 12:41 UTC, honzajavorek commented
Thank you! ❤️