feat: Replace deprecated audioop
Pycord-Development/pycord pull request #2176
Opened 2023-07-23 10:48 UTC by davidhozic

## Summary
This PR replaces the ``PCMVolumeTransformer.read()`` method with a Python equivalent, that does not use the ``audioop`` module, which is deprecated since Python 3.11 and will be removed in Python 3.13.

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-07-26 17:43 UTC, VincentRPS submitted a review, later dismissed
LGTM

2023-07-27 11:20 UTC, Om1609 commented
A python equivalent will not be nearly as close as the C one in terms of performance. Live audio is a heavy load and has to be low latency.

2023-07-27 11:24 UTC, VincentRPS commented
> A python equivalent will not be nearly as close as the C one in terms of performance. Live audio is a heavy load and has to be low latency.

I mean we can always rewrite it in Rust.

2023-07-27 11:25 UTC, VincentRPS commented
and also this largely uses python stdlib modules which from the seems of things are written in C in many places.

2023-07-27 11:33 UTC, Om1609 commented
> > A python equivalent will not be nearly as close as the C one in terms of performance. Live audio is a heavy load and has to be low latency.
> 
> I mean we can always rewrite it in Rust.

The whole voice stuff could be rewritten to Rust 😬

2023-07-27 11:33 UTC, Om1609 commented
> and also this largely uses python stdlib modules which from the seems of things are written in C in many places.

Possible to do actual performance tests?

2023-07-27 11:39 UTC, VincentRPS commented
> > > A python equivalent will not be nearly as close as the C one in terms of performance. Live audio is a heavy load and has to be low latency.
> > 
> > 
> > I mean we can always rewrite it in Rust.
> 
> The whole voice stuff could be rewritten to Rust 😬

only if :)

2023-07-27 17:08 UTC, davidhozic commented
audioop:
    ![image](https://github.com/Pycord-Development/pycord/assets/25441182/c670172e-14ab-45bb-8953-427cf2b17326)

Without audioop:
![image](https://github.com/Pycord-Development/pycord/assets/25441182/e2a197c6-8566-4adb-87b7-add0bfa29788)

Hardware:
OS Name	Microsoft Windows 10 Pro
Processor	AMD Ryzen 5 5600X 6-Core Processor, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)

2023-07-27 17:16 UTC, Om1609 commented
Hmm that sure is a difference.

Use `time.perf_counter_ns()` instead of `time.time()`. The result will be more accurate and will return ns instead of s

2023-07-27 17:19 UTC, Om1609 commented
Can we maintain and ship our own audioop C file? Dpy plans to do something like that

Or we could try Cython or maybe Rust?

2023-07-27 17:24 UTC, davidhozic commented
There, it's faster now:
![image](https://github.com/Pycord-Development/pycord/assets/25441182/bf27698a-71ef-4c22-902b-e801972b79b5)

2023-07-27 17:25 UTC, davidhozic commented
With time.perf_counter_ns():

![image](https://github.com/Pycord-Development/pycord/assets/25441182/26359ad7-c4be-4553-9347-26d609737482)

2023-07-27 17:26 UTC, davidhozic commented
```py
def timeit(f: Callable, ):
    def wrapper(*args, **kwargs):
        start = time.perf_counter_ns()
        result = f(*args, **kwargs)
        print(f"Elapsed: {(time.perf_counter_ns() - start)} ns")
        return result

    return wrapper
```

for anyone trying to benchmark:

![image](https://github.com/Pycord-Development/pycord/assets/25441182/f741f83f-e044-4702-abcd-4faba898225a)

2023-07-27 17:27 UTC, davidhozic commented
I can rewrite it in C if you'd like, possible compile it first with cython and then optimize?

2023-07-27 17:44 UTC, davidhozic commented
CPU running at 1 GHz, latest changes:
![image](https://github.com/Pycord-Development/pycord/assets/25441182/9365a06c-53ce-464c-8c6d-daac30212b13)
I think this should be more than enough optimized, since this function reads 20ms of audio.

2023-07-27 18:09 UTC, Lulalaby requested changes

2023-07-27 18:09 UTC, Lulalaby commented on CHANGELOG.md
> +- Replaced audioop (deprecated module) implementation of `PCMVolumeTransformer.read`
Move to bottom. New entries are appended

2023-07-28 08:02 UTC, davidhozic commented
R5 5600x 4.7 GHz
```
Elapsed: 31819500 ns
Elapsed: 1016100 ns
Elapsed: 868800 ns
Elapsed: 739800 ns
Elapsed: 897400 ns
Elapsed: 743300 ns
Elapsed: 732200 ns
Elapsed: 784500 ns
Elapsed: 840000 ns
Elapsed: 936100 ns
Elapsed: 909200 ns
Elapsed: 731400 ns
Elapsed: 887800 ns
Elapsed: 941000 ns
Elapsed: 950500 ns
Elapsed: 772200 ns
Elapsed: 922500 ns
Elapsed: 942000 ns
Elapsed: 1004100 ns
Elapsed: 964600 ns
Elapsed: 905800 ns
Elapsed: 1057200 ns
Elapsed: 936400 ns
Elapsed: 873700 ns
Elapsed: 1033400 ns
Elapsed: 887700 ns
Elapsed: 953700 ns
Elapsed: 946600 ns
Elapsed: 980300 ns
Elapsed: 797400 ns
Elapsed: 890200 ns
Elapsed: 1122800 ns
Elapsed: 1002900 ns
Elapsed: 939600 ns
Elapsed: 746800 ns
Elapsed: 747200 ns
Elapsed: 1389700 ns
Elapsed: 767300 ns
Elapsed: 950200 ns
Elapsed: 1132400 ns
Elapsed: 766400 ns
Elapsed: 995400 ns
Elapsed: 998400 ns
```

2023-07-29 22:02 UTC, Om1609 commented
Wow that is some real improvement 👍 

LGTM

2023-12-31 13:09 UTC, Dorukyum submitted a review, later dismissed

2023-12-31 13:09 UTC, Dorukyum commented on discord/player.py
> +
No need to mention this here, it's an internal code change.
```suggestion
```

2024-10-07 20:51 UTC, davidhozic commented
bump

2024-10-15 23:43 UTC, Lulalaby requested changes
Where does this come from

2024-10-15 23:45 UTC, Lulalaby requested changes

2024-10-15 23:45 UTC, Lulalaby commented on CHANGELOG.md
> +  subcommand group. ([#2275](https://github.com/Pycord-Development/pycord/pull/2275))
```suggestion
```

2024-10-16 17:33 UTC, davidhozic commented
> Where does this come from

The changelog thing? It was probably added through some weird auto-merge.

2024-10-17 12:49 UTC, Lulalaby approved these changes

2024-10-17 15:28 UTC, plun1331 approved these changes

2024-10-17 15:28 UTC, merged

2025-05-04 18:14 UTC, davidhozic commented
Are there any plans or are the main maintainters open for rewriting some of the audio functionalities in Rust (for performance reasons)?

2025-05-04 23:11 UTC, DA-344 commented
> Are there any plans or are the main maintainters open for rewriting some of the audio functionalities in Rust (for performance reasons)?

Py-cord is meant to be used in (almost) all machines, and writing Rust implementations will prevent some machines to use it anymore because they cannot compile such code.