ForumChannel default_reaction_emoji attribute
Pycord-Development/pycord pull request #2178
Opened 2023-07-23 13:15 UTC by davidhozic

## Summary
This implements #2174.

## Information
It adds ``default_reaction_emoji`` parameter to ``Guild.create_forum_channel()`` and ``default_reaction_emoji`` attribute to 
``ForumChannel``.

Additionally it renames private method ``PartialEmoji._to_forum_tag_payload()`` => ``PartialEmoji._to_forum_reaction_payload()`` (possibly breaking change)

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-07-23 18:58 UTC, plun1331 submitted a review, later dismissed
`edit` and `create` methods could accept a string representation of the emoji (`<a:emoji_name:emoji_id>`) for convenience, similarly to how `Message.add_reaction` accepts a string repr of a custom emoji (although it's implemented differently due to how the endpoint works)

other than that lgtm

2023-07-23 19:47 UTC, davidhozic commented
> `edit` and `create` methods could accept a string representation of the emoji (`<a:emoji_name:emoji_id>`) for convenience, similarly to how `Message.add_reaction` accepts a string repr of a custom emoji (although it's implemented differently due to how the endpoint works)
> 
> other than that lgtm

It does accept ``<a:emoji_name:emoji_id>``, I'll update the docstrings to make it clearer.

2023-07-23 19:52 UTC, JustaSqu1d requested changes
Fix documentation formatting

See [here](https://pycord--2178.org.readthedocs.build/en/2178/api/models.html#discord.Guild.create_forum_channel), for example.

2023-07-23 21:04 UTC, JustaSqu1d reviewed
Move the changelog entry to the bottom

2023-07-23 21:04 UTC, JustaSqu1d commented on CHANGELOG.md
> +  ([#2178](https://github.com/Pycord-Development/pycord/pull/2178))
Entries should be added in chronological order.

2023-07-24 01:56 UTC, plun1331 commented
> > `edit` and `create` methods could accept a string representation of the emoji (`<a:emoji_name:emoji_id>`) for convenience, similarly to how `Message.add_reaction` accepts a string repr of a custom emoji (although it's implemented differently due to how the endpoint works)
> > other than that lgtm
> 
> It does accept `<a:emoji_name:emoji_id>`, I'll update the docstrings to make it clearer.

It didn't look like it did at a first glance, sorry about that

2023-07-24 01:56 UTC, plun1331 submitted a review, later dismissed

2023-07-24 22:58 UTC, JustaSqu1d requested changes

2023-07-24 22:58 UTC, JustaSqu1d commented on CHANGELOG.md
> +  `default_reaction_emoji`.
```suggestion
- Added `default_reaction_emoji` parameter to `Guild.create_forum_channel()`, `ForumChannel.create_forum_channel()`, and
`ForumChannel.edit_forum_channel()` functions:
```

2023-07-24 23:06 UTC, JustaSqu1d commented on CHANGELOG.md
> +  `default_reaction_emoji`.
Probably also add a separate changelog entry about the `default_reaction_emoji` attribute.

2023-07-24 23:28 UTC, Lulalaby commented on CHANGELOG.md
> +  ([#2178](https://github.com/Pycord-Development/pycord/pull/2178))
```suggestion
- Added `ForumChannel.default_reaction_emoji` attribute.
  ([#2178](https://github.com/Pycord-Development/pycord/pull/2178))
- Added `default_reaction_emoji` parameter to `Guild.create_forum_channel()` and
  `ForumChannel.edit()` methods.
  ([#2178](https://github.com/Pycord-Development/pycord/pull/2178))
```

2023-07-24 23:33 UTC, JustaSqu1d reviewed
What does this do

https://github.com/davidhozic/pycord/blob/feat/default_forum_reaction/discord/abc.py#L511-L514

2023-07-25 00:09 UTC, davidhozic commented
> What does this do

Which thing, I don't see any reference in your reply?

2023-07-25 23:12 UTC, davidhozic commented
> What does this do
> 
> https://github.com/davidhozic/pycord/blob/feat/default_forum_reaction/discord/abc.py#L511-L514

It checks if the key exists - if parameter was given to edit. If it doesn't it will raise an Exception and not execute the else statement

2023-12-14 17:39 UTC, plun1331 approved these changes

2023-12-14 18:20 UTC, Lulalaby approved these changes

2023-12-14 18:20 UTC, merged