fix: when task's `tzinfo` is not `None` or UTC, the task loops infinitely
Pycord-Development/pycord pull request #2196
Opened 2023-08-05 06:26 UTC by SorameHato

## Summary
Please see issue #2187

If task's tzinfo is not UTC and task's time is between UTC 00:00 and destination timezone's 00:00, it loop infinitely until destination timezone's 00:00(countries in east of UTC timezone like Eastern Europe, Korea, Japan, Australia) or UTC 00:00(countries in west of UTC timezone like USA, Canada) comes.
<details>
<summary>Test Log (KST 08:47 = UTC 23:47)</summary>
<p>

```
# logged in as : 하늘봇(PyCord 2.5 테스트)
# logged in at : 2023-08-05 08:47:11.900681+0900 (spent 0:00:03.079106)
# repo : Pycord-Development/pycord

# TEST A1 (Single time whose tzinfo is UTC)
# Task's time : 23:47:12.321575+00:00
# First Run : 2023-08-05 08:47:12.321575+09:00
time : 2023-08-05 08:47:12.321516+09:00, count : 0, next loop : 2023-08-06 08:47:12.321575+09:00
# Current loop : 0 | It works properly.

# TEST A2 (Single time whose tzinfo is KST)
# Task's time : 08:47:12.571575+09:00
# First Run : 2023-08-05 08:47:12.571575+09:00
time : 2023-08-05 08:47:12.572462+09:00, count : 0, next loop : 2023-08-05 08:47:12.571575+09:00
time : 2023-08-05 08:47:12.572462+09:00, count : 1, next loop : 2023-08-05 08:47:12.571575+09:00
time : 2023-08-05 08:47:12.572462+09:00, count : 2, next loop : 2023-08-05 08:47:12.571575+09:00
time : 2023-08-05 08:47:12.572462+09:00, count : 3, next loop : 2023-08-05 08:47:12.571575+09:00
# Current loop : 7086 | Infinity Loop has occured.

# TEST A3 (Single time which is naive)
# Task's time : 23:47:12.821575
# First Run : 2023-08-05 08:47:12.821575+09:00
time : 2023-08-05 08:47:12.816994+09:00, count : 0, next loop : 2023-08-06 08:47:12.821575+09:00
# Current loop : 0 | It works properly.

# TEST B1 (Multiple time whose tzinfo is UTC)
# Task's time : [datetime.time(23, 47, 13, 71575, tzinfo=datetime.timezone.utc), datetime.time(23, 47, 13, 321575, tzinfo=datetime.timezone.utc)]
# First Run : 2023-08-05 08:47:13.071575+09:00
time : 2023-08-05 08:47:13.069588+09:00, count : 0, next loop : 2023-08-05 08:47:13.321575+09:00
time : 2023-08-05 08:47:13.322405+09:00, count : 1, next loop : 2023-08-06 08:47:13.071575+09:00
# Current loop : 1 | It works properly.

# TEST B2 (Multiple time whose tzinfo is KST)
# Task's time : [datetime.time(8, 47, 13, 571575, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))), datetime.time(8, 47, 13, 821575, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))]
# First Run : 2023-08-05 08:47:13.571575+09:00
time : 2023-08-05 08:47:13.571558+09:00, count : 0, next loop : 2023-08-05 08:47:13.821575+09:00
time : 2023-08-05 08:47:13.829117+09:00, count : 1, next loop : 2023-08-05 08:47:13.571575+09:00
time : 2023-08-05 08:47:13.829117+09:00, count : 2, next loop : 2023-08-05 08:47:13.571575+09:00
time : 2023-08-05 08:47:13.829117+09:00, count : 3, next loop : 2023-08-05 08:47:13.571575+09:00
# Current loop : 6755 | Infinity Loop has occured.

# TEST B3 (Multiple time which is naive)
# Task's time : [datetime.time(23, 47, 14, 71575), datetime.time(23, 47, 14, 321575)]
# First Run : 2023-08-05 08:47:14.071575+09:00
time : 2023-08-05 08:47:14.066043+09:00, count : 0, next loop : 2023-08-05 08:47:14.321575+09:00
time : 2023-08-05 08:47:14.322804+09:00, count : 1, next loop : 2023-08-06 08:47:14.071575+09:00
# Current loop : 1 | It works properly.

# TEST C (Interval = 0.25 sec)
# First Run : 2023-08-05 08:47:14.447889+09:00
time : 2023-08-05 08:47:14.447889+09:00, count : 0, next loop : 2023-08-05 08:47:14.697889+09:00
time : 2023-08-05 08:47:14.697978+09:00, count : 1, next loop : 2023-08-05 08:47:14.947978+09:00
time : 2023-08-05 08:47:14.948891+09:00, count : 2, next loop : 2023-08-05 08:47:15.198891+09:00
# Current loop : 2 | It works properly.

# Total Result = OXOOXOO
```
</p>
</details>

I resolved that bug by making `datetime.datetime.now` in `_get_next_sleep_time` of `discord.ext.tasks` to represents timezone of task's time.
<details>
<summary>Test Log (KST 08:48 = UTC 23:48)</summary>
<p>

```
# logged in as : 하늘봇(PyCord 2.5 테스트)
# logged in at : 2023-08-05 08:48:22.247804+0900 (spent 0:00:03.069594)
# repo : SorameHato/pycord-task-bug-resolve

# TEST A1 (Single time whose tzinfo is UTC)
# Task's time : 23:48:22.678210+00:00
# First Run : 2023-08-05 08:48:22.678210+09:00
time : 2023-08-05 08:48:22.672608+09:00, count : 0, next loop : 2023-08-06 08:48:22.678210+09:00
# Current loop : 0 | It works properly.

# TEST A2 (Single time whose tzinfo is KST)
# Task's time : 08:48:22.928210+09:00
# First Run : 2023-08-05 08:48:22.928210+09:00
time : 2023-08-05 08:48:22.933934+09:00, count : 0, next loop : 2023-08-06 08:48:22.928210+09:00
# Current loop : 0 | It works properly.

# TEST A3 (Single time which is naive)
# Task's time : 23:48:23.178210
# First Run : 2023-08-05 08:48:23.178210+09:00
time : 2023-08-05 08:48:23.176116+09:00, count : 0, next loop : 2023-08-06 08:48:23.178210+09:00
# Current loop : 0 | It works properly.

# TEST B1 (Multiple time whose tzinfo is UTC)
# Task's time : [datetime.time(23, 48, 23, 428210, tzinfo=datetime.timezone.utc), datetime.time(23, 48, 23, 678210, tzinfo=datetime.timezone.utc)]
# First Run : 2023-08-05 08:48:23.428210+09:00
time : 2023-08-05 08:48:23.421220+09:00, count : 0, next loop : 2023-08-05 08:48:23.678210+09:00
time : 2023-08-05 08:48:23.679066+09:00, count : 1, next loop : 2023-08-06 08:48:23.428210+09:00
# Current loop : 1 | It works properly.

# TEST B2 (Multiple time whose tzinfo is KST)
# Task's time : [datetime.time(8, 48, 23, 928210, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))), datetime.time(8, 48, 24, 178210, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))]
# First Run : 2023-08-05 08:48:23.928210+09:00
time : 2023-08-05 08:48:23.925176+09:00, count : 0, next loop : 2023-08-05 08:48:24.178210+09:00
time : 2023-08-05 08:48:24.179965+09:00, count : 1, next loop : 2023-08-06 08:48:23.928210+09:00
# Current loop : 1 | It works properly.

# TEST B3 (Multiple time which is naive)
# Task's time : [datetime.time(23, 48, 24, 428210), datetime.time(23, 48, 24, 678210)]
# First Run : 2023-08-05 08:48:24.428210+09:00
time : 2023-08-05 08:48:24.426130+09:00, count : 0, next loop : 2023-08-05 08:48:24.678210+09:00
time : 2023-08-05 08:48:24.679571+09:00, count : 1, next loop : 2023-08-06 08:48:24.428210+09:00
# Current loop : 1 | It works properly.

# TEST C (Interval = 0.25 sec)
# First Run : 2023-08-05 08:48:24.822163+09:00
time : 2023-08-05 08:48:24.822163+09:00, count : 0, next loop : 2023-08-05 08:48:25.072163+09:00
time : 2023-08-05 08:48:25.073133+09:00, count : 1, next loop : 2023-08-05 08:48:25.323133+09:00
time : 2023-08-05 08:48:25.324065+09:00, count : 2, next loop : 2023-08-05 08:48:25.574065+09:00
# Current loop : 2 | It works properly.

# Total Result = OOOOOOO
```
</p>
</details>

<details>
<summary>Source Code of Test File</summary>
<p>

```
# coding: utf-8
import discord
import os
import asyncio
import sys
from discord.ext import commands, tasks
from datetime import datetime as dt
from datetime import timezone as tz
from datetime import timedelta as td
from datetime import time
from time import time as epochtime
import pathlib
intents = discord.Intents.all()
bot = discord.Bot(intents=intents)
hanul_ver = "0.0 rev 128 (2023-08-03 10:42)"
bot.hanul_ver = hanul_ver
result = ''
delay = 3.5 #Please set this time to delay of logging in to discord
now1 = dt.now(tz.utc) # aware (tz = UTC)
now2 = now1.astimezone(tz=tz(td(hours=9))) # aware (tz = KST)
now3 = now1.replace(tzinfo=None) # naive (UTC)
time_a1 = (now1 + td(seconds = delay)).timetz()
time_a2 = (now2 + td(seconds = delay, microseconds = 250000)).timetz()
time_a3 = (now3 + td(seconds = delay, microseconds = 500000)).timetz()
time_b1 = [(now1 + td(seconds = delay, microseconds = 750000)).timetz(), (now1 + td(seconds = delay+1)).timetz()]
time_b2 = [(now2 + td(seconds = delay+1, microseconds = 250000)).timetz(), (now2 + td(seconds = delay+1, microseconds = 500000)).timetz()]
time_b3 = [(now3 + td(seconds = delay+1, microseconds = 750000)).timetz(), [...]

2023-08-14 21:19 UTC, JustaSqu1d requested changes

2023-08-14 21:19 UTC, JustaSqu1d commented on CHANGELOG.md
> +  UTC
```suggestion
- Fixed infinity loop of `discord.ext.tasks.Loop` when task's `tzinfo` is not `None` or UTC
([#2196](https://github.com/Pycord-Development/pycord/pull/2196))
```

2023-08-15 07:06 UTC, Dorukyum submitted a review, later dismissed
Haven't tested, just making a stylistic review

2023-08-15 07:06 UTC, Dorukyum commented on discord/ext/tasks/__init__.py
> +                    )
```suggestion
                    datetime.datetime.now(self._time[0].tzinfo or datetime.timezone.utc)
```

2023-08-15 07:06 UTC, Dorukyum commented on discord/ext/tasks/__init__.py
> +                ).timetz()
```suggestion
                > datetime.datetime.now(next_time.tzinfo or datetime.timezone.utc).timetz()
```

2023-08-15 07:06 UTC, Dorukyum commented on discord/ext/tasks/__init__.py
> +                    ),
```suggestion
                    datetime.datetime.now(next_time.tzinfo or datetime.timezone.utc),
```

2023-08-15 07:06 UTC, Dorukyum commented on discord/ext/tasks/__init__.py
> +                    )
```suggestion
                    datetime.datetime.now(next_time.tzinfo or datetime.timezone.utc)
```

2023-08-15 20:45 UTC, Lulalaby commented
> It works fine for me

That's not the point here, We have to test it as well lol.
Everyone can say "works on my machine" lmfao.

2023-09-17 07:50 UTC, Middledot approved these changes
Tested

2023-09-22 01:57 UTC, JustaSqu1d approved these changes

2023-11-22 00:38 UTC, benjo121ben commented
Hi, been having the same issue. 
Not super familiar with github yet, has issue been integrated into a future version?

2023-11-26 15:32 UTC, Dorukyum commented on CHANGELOG.md
> +  UTC ([#2196](https://github.com/Pycord-Development/pycord/pull/2196))
```suggestion
- Fixed tasks looping infinitely when `tzinfo` is neither `None` nor UTC.
  ([#2196](https://github.com/Pycord-Development/pycord/pull/2196))
```

2023-11-26 15:32 UTC, Dorukyum submitted a review, later dismissed

2023-11-26 15:35 UTC, Dorukyum approved these changes

2023-11-26 15:39 UTC, merged