feat: implement monetization
Pycord-Development/pycord pull request #2273
Opened 2023-12-01 21:56 UTC by plun1331

## Summary

Implements monetization as documented under https://discord.com/developers/docs/monetization

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2023-12-02 17:57 UTC, Nzii3 approved these changes

2024-02-01 00:32 UTC, Lulalaby requested changes

2024-02-01 00:32 UTC, Lulalaby commented on discord/enums.py
> +
might miss the enum for owner type
```cs
public enum EntitlementOwnerType
{
	/// <summary>
	/// Owner id is a guild.
	/// </summary>
	GuildSubscription = 1,

	/// <summary>
	/// Owner id is an user.
	/// </summary>
	UserSubscription = 2
}
```

2024-02-01 00:32 UTC, Lulalaby commented on discord/guild.py
> +            "owner_type": 1,
use ownertype enum

2024-02-01 00:32 UTC, Lulalaby commented on discord/monetization.py
> +class Entitlement(Hashable):
it's missing `guild_id`

2024-02-01 00:32 UTC, Lulalaby commented on discord/user.py
> +            "owner_type": 2,
use ownertype enum

2024-02-01 00:32 UTC, Lulalaby commented
+ merge conflicts

2024-02-01 01:01 UTC, Lulalaby submitted a review, later dismissed

2024-02-01 01:01 UTC, Lulalaby commented
![image](https://github.com/Pycord-Development/pycord/assets/14029133/456ad2e5-2472-4a47-b799-047e985a2e0e)

2024-02-01 01:05 UTC, Lulalaby approved these changes

2024-02-01 01:06 UTC, merged