fix(ext.commands): Fixed required=False when default is None
Pycord-Development/pycord pull request #2282
Opened 2023-12-09 16:50 UTC by Krutyi-4el

## Summary

https://github.com/Pycord-Development/pycord/issues/2089#issuecomment-1836791234

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2023-12-09 17:51 UTC, Dorukyum commented
I don't understand, there's no way `x or y` returns `False` when one side is `True`

2023-12-09 18:10 UTC, Lulalaby commented
Yeah same thought here. Closing it as invalid.

2023-12-09 22:07 UTC, Krutyi-4el commented
@Lulalaby @Dorukyum is this code valid?

```python
@bot.bridge_command()
async def test_no_default(ctx, text: Option(str, required=False)):
    await ctx.respond(text or "hello")```

I think it should work but it doesn't because the default is None.

2023-12-09 23:42 UTC, plun1331 commented
> I don't understand, there's no way `x or y` returns `False` when one side is `True`

The issue seems to be that it's returning `True` when it logically shouldn't (`required` is `False`, however `default` is `None`)

`default` being `None` should not change the behavior of `required`

2023-12-10 14:26 UTC, Dorukyum commented
> `default` being `None` should not change the behavior of `required`

Isn't that how it's always been? `Option(...)` would be required while `Option(..., default=None)` would be optional.

2023-12-10 16:07 UTC, Krutyi-4el commented
> > `default` being `None` should not change the behavior of `required`
> 
> Isn't that how it's always been? `Option(...)` would be required while `Option(..., default=None)` would be optional.

Yes, but it didn't (and still doesn't) work for bridge commands invoked via prefix.

This PR fixes the issue.

2023-12-10 21:29 UTC, plun1331 commented
> > `default` being `None` should not change the behavior of `required`
> 
> Isn't that how it's always been? `Option(...)` would be required while `Option(..., default=None)` would be optional.

But if required is `False` with default being `None`, it automatically flips `required` to `True`

2023-12-10 22:04 UTC, Krutyi-4el commented
> But if required is `False` with default being `None`, it automatically flips `required` to `True` (at least, that's my understanding of this pr)

Yes. Because of this the command above doesn't work without the argument.
The most confusing part is that it works when invoked as a slash command.

By the way, looks like `Option` alrea

2023-12-10 22:04 UTC, Krutyi-4el commented
Missclick 😅

2023-12-11 06:42 UTC, Dorukyum commented
> By the way, looks like `Option` already sets its `.required` attribute properly. Maybe it should be just `required = param.annotation.required`.

My bad, I understand the pr now and I think you're right. We can't do `and default is None` because `default` doesn't have to be `None`. Like you said, `Option` already sets `required` meaning we can just use `required = param.annotation.required` here.

2023-12-11 06:43 UTC, Dorukyum requested changes

2023-12-11 06:43 UTC, Dorukyum commented on discord/ext/commands/core.py
> +            required = param.annotation.required and default is None
```suggestion
            required = param.annotation.required
```

2023-12-11 12:41 UTC, Lulalaby approved these changes

2023-12-14 17:09 UTC, merged