feat: add applied_tags parameter to Webhook.send()
Pycord-Development/pycord pull request #2322
Opened 2024-01-17 11:47 UTC by tyrantlink

## Summary

Added applied_tags parameter to Webhook.send(), allowing for forum channel tags to be applied through a webhook.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-01-18 07:10 UTC, Dorukyum requested changes

2024-01-18 10:54 UTC, tyrantlink commented on discord/webhook/async_.py
> +
Simply applying this suggestion completely broke the formatting, so for now I just changed the versionadded to 2.5

2024-01-18 12:44 UTC, Dorukyum commented
Docs should be fine now, will approve after testing the parameter myself just in case.

2024-01-20 05:42 UTC, Dorukyum requested changes
I think the parameter should accept a list of `ForumTag`s too to mirror the one in `ForumChannel.create_thread`. Could use a type of `list[Snowflake | ForumTag]` and then take IDs from the tag objects.

2024-01-21 13:57 UTC, Dorukyum approved these changes
I'll implement the suggestion I made earlier in a different pull request, thanks.

2024-01-22 16:53 UTC, merged