fix: Replace deprecated pkg_resources with importlib.metadata to clear DeprecationWarning
Pycord-Development/pycord pull request #2392
Opened 2024-03-13 13:51 UTC by Revnoplex

## Summary
Replaced `pkg_resources` with `importlib.metadata` as favoured [here](https://setuptools.pypa.io/en/latest/pkg_resources.html). Hence replacing `get_distribution()` with `version()`.

This clears the following deprecation warning:
```
/home/username/venv/lib/python3.11/site-packages/discord/__main__.py:33: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes. (unsure if needed)

2024-03-13 14:10 UTC, Lulalaby approved these changes

2024-03-13 15:32 UTC, plun1331 commented
Should we have a changelog entry for this?

2024-03-13 15:52 UTC, JustaSqu1d commented
> Should we have a changelog entry for this?

I don't think so because it doesn't affect the end-user?

2024-03-13 20:59 UTC, plun1331 commented
> > Should we have a changelog entry for this?
> 
> I don't think so because it doesn't affect the end-user?

It removes a deprecation warning that appears in their terminal

2024-03-15 05:22 UTC, JustaSqu1d requested changes
Please add a changelog entry

2024-03-15 06:47 UTC, Revnoplex commented
alr, I'll get onto it soon

2024-03-15 07:44 UTC, Revnoplex commented
Done

2024-03-15 07:46 UTC, Lulalaby commented on CHANGELOG.md
> +  by replacing the depricated module.
```suggestion
  by replacing the deprecated module.
```

2024-03-15 14:51 UTC, plun1331 approved these changes

2024-03-15 18:55 UTC, JustaSqu1d requested changes

2024-03-15 18:55 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Fixed a `DeprecationWarning` from being displayed when running `python -m discord -v`
```suggestion
- Fixed a deprecation warning from being displayed when running `python -m discord -v`
```

2024-03-16 03:44 UTC, plun1331 approved these changes

2024-03-17 01:55 UTC, Lulalaby approved these changes

2024-03-17 01:56 UTC, merged