Ability to change/set the banner of the bot.
Pycord-Development/pycord pull request #2396
Opened 2024-03-15 21:45 UTC by Braandn

Added "banner" to the edit function.

Till now the official discord docs are not updated, but its is working.

ref: https://github.com/discord/discord-api-docs/pull/6710

## Summary

## Information

- [ ] This PR fixes an issue.
- [ x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ x] I have searched the open pull requests for duplicates.
- [x ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-03-16 03:51 UTC, plun1331 requested changes
Please add a changelog

2024-03-16 03:51 UTC, plun1331 commented on discord/user.py
> +            The only image formats supported for uploading is JPEG and PNG and GIF.
```suggestion
            The only image formats supported for uploading are JPEG, PNG, and GIF.
```

2024-03-16 03:51 UTC, plun1331 commented on discord/user.py
>              The edit is no longer in-place, instead the newly edited client user is returned.
Add a version changed
```suggestion
        .. versionchanged:: 2.0
            The edit is no longer in-place, instead the newly edited client user is returned.
            
        .. versionchanges:: 2.6
            The ``banner`` keyword-only parameter was added.
```

2024-03-16 05:44 UTC, plun1331 commented on discord/user.py
> +        .. versionchanges:: 2.6
mb
```suggestion
        .. versionchanged:: 2.6
```

2024-03-17 01:06 UTC, Lulalaby requested changes
Changelog

2024-03-17 07:12 UTC, plun1331 approved these changes

2024-03-17 07:52 UTC, Lulalaby approved these changes

2024-03-17 07:55 UTC, merged