fix: Duplication in bridge command help
Pycord-Development/pycord pull request #2415
Opened 2024-04-05 13:06 UTC by Blue-Robin-Taken

## Summary
This pull request is for the issue https://github.com/Pycord-Development/pycord/issues/2306

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-04-06 17:22 UTC, Lulalaby submitted a review, later dismissed

2024-04-09 15:07 UTC, JustaSqu1d requested changes

2024-04-09 15:07 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Fixed duplication in bridge command help.
```suggestion
- Fixed `BridgeCommand` duplication in default help commands.
```

2024-04-09 15:07 UTC, JustaSqu1d commented on discord/ext/commands/help.py
> +                continue
There is an edge case of subcommands not registering (e.g. "foo bar" and "goo bar").

2024-04-09 20:29 UTC, Blue-Robin-Taken commented
I haven't checked if the code works yet but I will when I get home

2024-05-06 02:16 UTC, plun1331 commented
> I haven't checked if the code works yet but I will when I get home

Any updates?

2024-05-06 02:46 UTC, Blue-Robin-Taken commented
Thanks for the reminder, I currently do not have time atm to check it still 💀
finals are coming up and I *might* be able to check tomorrow

2024-05-17 14:18 UTC, Blue-Robin-Taken commented
I'm definitely going to wait to do this after final exams or maybe if I have time this weekend

2024-08-07 05:57 UTC, JustaSqu1d commented on CHANGELOG.md
> +  ([#2415](https://github.com/Pycord-Development/pycord/pull/2415))
Move changelog to new section

2024-08-10 11:05 UTC, Lulalaby commented
@Blue-Robin-Taken

2024-08-10 18:06 UTC, Blue-Robin-Taken commented
I just started junior year and if I have time today (cause it's the weekend) I'll get on it
Thanks for the notifs @Lulalaby !

2024-08-10 18:07 UTC, Lulalaby commented
Thanks, ping me when ready to review

2024-09-10 01:29 UTC, ChickenDevs commented
@Blue-Robin-Taken Just wanted to follow up on this PR!

2025-01-05 14:30 UTC, Dorukyum commented
Stale, superseded by #2656.

2025-01-05 14:30 UTC, closed without merging