fix: Guild.query_members may accept empty query and limit
Pycord-Development/pycord pull request #2419
Opened 2024-04-11 14:28 UTC by NeloBlivion

## Summary

When requesting guild members [through the gateway](https://discord.com/developers/docs/topics/gateway-events#request-guild-members), you can pass an empty string `query` and `limit=0` to recieve all members. This adjusts `Guild.query_members` to accept `limit=None` (or `0`) to allow this behavior, though the default `limit` isn't changed to avoid breaking, and interprests `query=None` as an empty string.
As such, all guild members can be quickly recieved (and cached) through `await guild.query_members(limit=None)`.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-04-12 15:17 UTC, plun1331 requested changes
please :clap: add 👏 a 👏 change :clap: log :clap: entry

2024-04-12 15:22 UTC, JustaSqu1d requested changes

2024-04-12 15:22 UTC, JustaSqu1d commented on discord/guild.py
> +                raise ValueError("Must pass query, user_ids, or set limit to None")
```suggestion
                raise ValueError("Must pass query or user_ids, or set limit to None")
```

2024-04-14 04:45 UTC, JustaSqu1d approved these changes

2024-04-14 05:05 UTC, Lulalaby submitted a review, later dismissed

2024-04-15 09:36 UTC, Dorukyum requested changes

2024-04-15 09:36 UTC, Dorukyum commented on discord/guild.py
> +            If you specify a ``query`` or ``user_ids``, this must be between 1 and 100. Defaults to 5.
```suggestion
            The maximum number of members to send back. If no query is passed, passing ``None`` returns all members.
            If a ``query`` or ``user_ids`` is passed, must be between 1 and 100. Defaults to 5.
```

2024-04-15 09:36 UTC, Dorukyum commented on discord/guild.py
> +        cache: Optional[:class:`bool`]
This is not optional. It defaults to `True` which is a bool.
```suggestion
        cache: :class:`bool`
```

2024-04-16 17:38 UTC, plun1331 approved these changes

2024-04-16 17:39 UTC, JustaSqu1d approved these changes

2024-04-16 20:01 UTC, merged