docs: limits on integer and number option types
Pycord-Development/pycord pull request #2462
Opened 2024-05-26 23:00 UTC by JustaSqu1d

## Summary

Many people seem to use `SlashCommandOptionType.integer` or similar for IDs. This change serves to clarify its limitations.

The superscripts seem to have extra spacing because of monospaces, but this looks fine on the documentation.

Looking for feedback about whether the ID notes for `SlashCommandOptionType.number` are necessary or can be removed.

I'm not sure how to remove ambiguity with this change and with `Option.max_value` and `Option.min_value` since those can be used to change the range of accepted values.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-05-27 17:56 UTC, plun1331 commented
Should probably just replace the docs for that instead of making a note

2024-05-28 04:55 UTC, Dorukyum requested changes

2024-05-28 04:55 UTC, Dorukyum commented on docs/api/enums.rst
> +            IDs, such as 881224361015672863, are often too for this input type.
```suggestion
            IDs, such as 881224361015672863, are often too big for this input type.
```
or any other adjective

2024-05-28 04:55 UTC, Dorukyum commented on docs/api/enums.rst
> +            IDs, such as 881224361015672863, are often too for this input type.
```suggestion
            IDs, such as 881224361015672863, are often too big for this input type.
```

2024-05-28 04:55 UTC, Dorukyum commented on docs/api/enums.rst
> +            IDs, such as 881224361015672863, are often too for this input type.
```suggestion
            IDs, such as 881224361015672863, are often too big for this input type.
```

2024-05-28 04:58 UTC, Dorukyum commented
Does specifying the limits as exponents of 2 actually help with anything?

2024-05-28 05:02 UTC, JustaSqu1d commented
> Does specifying the limits as exponents of 2 actually help with anything?

Would you rather 9.0071992547*10^15?

2024-05-28 07:26 UTC, Dorukyum commented
> > Does specifying the limits as exponents of 2 actually help with anything?
> 
> 
> 
> Would you rather have 9.0071992547*10^15? Or am I misunderstanding the question?

You did get that right and I did mean that, but now I think we should specify both, like "9007199254740992 (2^53)".

2024-06-22 10:28 UTC, Dorukyum approved these changes

2024-06-28 04:36 UTC, Lulalaby approved these changes

2024-06-28 04:39 UTC, merged