fix: enum option issues
Pycord-Development/pycord pull request #2463
Opened 2024-05-26 23:07 UTC by NeloBlivion

## Summary

Makes two changes for better enum support in options:
- If an enum's docstring is greater than 100 characters, truncate it (fixes issues on Python 3.11)
- If an enum has more than 25 values, use `basic_autocomplete` instead of `choices` and forces the type back to string.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-05-26 23:16 UTC, JustaSqu1d commented
It would be nice if this behavior was documented somewhere

2024-05-27 01:06 UTC, Lulalaby commented
What squid said

2024-06-06 22:39 UTC, Icebluewolf requested changes

2024-06-06 22:39 UTC, Icebluewolf commented on discord/commands/options.py
>                  description = inspect.getdoc(input_type)
What is the point of using `getdoc`? I think `cleandoc` is a better choice here. `getdoc` calls `cleandoc` but it also inherits docstrings from parents if the class does not have one. There is no reason that someone would want the description of their command to be the docstring for `Enum` or `DiscordEnum`.
```suggestion
                description = inspect.cleandoc(input_type.__doc__)
```

2024-06-22 10:26 UTC, Dorukyum commented
@NeloBlivion see suggestions

2024-07-01 11:33 UTC, Lulalaby approved these changes

2024-07-01 11:36 UTC, merged