fix: Missing slots attributes, wrong variable type, duplicate http methods
Pycord-Development/pycord pull request #2500
Opened 2024-07-16 22:25 UTC by Readeem

## Summary

I was just checking new update changes and I've noticed these small issues I fixed here in this PR.

**What was fixed:**
* Removed duplicated methods in `HTTPClient` class (might be breaking change but I don't think so, these weren't used)
* Fixed missed `stacklevel` parameter in `warn_deprecated` function call inside `deprecated` decorator in utils
* Fixed typehint in `ConnectionState._polls` incorrectly specified as `Guild` instead of `Poll`
* Fixed missing `__slots__` attributes in `RawReactionClearEmojiEvent` class
* Fixed missing `__slots__` attributes in `RawMessagePollVoteEvent` class
* Fixed `default_sort_order` variable type being `int` instead of typehinted `SortOrder` enum in `ForumChannel` class

I tested every fix, including checking type of `default_sort_order` variable.
If there's something wrong with duplicated method removals in `HTTPClient` class, I can revert these changes.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-07-16 23:54 UTC, Lulalaby commented
that definitely needs a changelog
u can skip changelog for the first change tho

2024-07-16 23:56 UTC, Lulalaby approved these changes

2024-07-17 08:39 UTC, Readeem commented
Ready to be merged

2024-07-17 08:49 UTC, Lulalaby submitted a review, later dismissed

2024-08-07 05:45 UTC, JustaSqu1d requested changes

2024-08-07 05:45 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Fixed `default_sort_order` variable type being `int` instead of typehinted `SortOrder`
```suggestion
- Fixed `default_sort_order` attribute type being `int` instead of typehinted `SortOrder`
```

2024-08-07 05:45 UTC, JustaSqu1d commented on CHANGELOG.md
> +  `deprecated` decorator in utils.
```suggestion
- Fixed missing `stacklevel` parameter in `warn_deprecated` function call inside
  `deprecated` decorator in utils.
```

2024-08-07 05:55 UTC, JustaSqu1d requested changes

2024-08-07 05:55 UTC, JustaSqu1d commented on CHANGELOG.md
> +  `Poll`. ([#2500](https://github.com/Pycord-Development/pycord/pull/2500))
```suggestion
- Fixed the typehint in `ConnectionState._polls` to reflect actual behavior, changing it from `Guild` to `Poll`. ([#2500](https://github.com/Pycord-Development/pycord/pull/2500))
```

2024-08-29 18:35 UTC, plun1331 submitted a review, later dismissed

2024-08-29 18:49 UTC, plun1331 approved these changes
damn precommit

2024-08-29 18:50 UTC, Lulalaby approved these changes

2024-08-29 18:50 UTC, merged