feat: Member.display_banner
Pycord-Development/pycord pull request #2556
Opened 2024-08-19 22:19 UTC by MattyTheHacker

## Summary

Implement Member.display_banner as per #2516 

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-08-19 23:10 UTC, Lulalaby requested changes
Changelog

2024-08-20 13:44 UTC, Lulalaby requested changes

2024-08-20 13:44 UTC, Lulalaby commented on CHANGELOG.md
> +
```suggestion
```
We don't do newlines between entries

2024-08-20 13:46 UTC, Lulalaby approved these changes

2024-08-21 14:30 UTC, MattyTheHacker commented on discord/asset.py
> +            url=f"{cls.BASE}/guilds/{guild_id}/users/{member_id}/banners/{banner}.{format}?size=1024",
Do you have a preference as to which to use? I did `1024` because that's what `_from_guild_avatar` used.

2024-08-27 19:18 UTC, Dorukyum commented
I changed both sizes to 512 for consistency.

2024-08-27 19:27 UTC, Dorukyum requested changes
Testing required

2024-08-27 22:44 UTC, yoggys commented
> Testing required

its missing some things, rn not working

2024-08-27 22:49 UTC, yoggys requested changes

2024-08-27 22:49 UTC, yoggys commented on discord/member.py
> +        )
```suggestion
        if self._banner is None:
            return None
        return Asset._from_guild_banner(
            self._state, self.guild.id, self.id, self._banner
        )
```

You should also add:
- to __init__
`self._banner: str | None = data.get("banner")`
- to _copy
`self._banner = member._banner`
- to _update
`self._banner = data.get("banner")`

2024-08-27 23:08 UTC, yoggys commented
@MattyTheHacker please also include:
```py
__slots__ = (
        ...
        "_banner",
        ...
    )
```

2024-08-27 23:28 UTC, yoggys commented
working good rn 👍

2024-08-27 23:53 UTC, yoggys approved these changes

2024-08-28 01:33 UTC, NeloBlivion commented
Thank you! Some notes:
- Main PR is still a draft, so might need to wait before merging https://github.com/discord/discord-api-docs/pull/6986
- When adding new fields from the API, make sure the respective TypedDict in `types` is updated (in this case, `types/member.py` -> `Member`)

2024-08-28 02:05 UTC, Lulalaby commented
We don't need to wait for the pr because it's live in stable already. Discord is just behind schedule

2024-08-28 23:00 UTC, plun1331 submitted a review, later dismissed

2024-08-29 01:44 UTC, Lulalaby approved these changes

2024-08-29 16:51 UTC, Dorukyum approved these changes

2024-08-29 16:51 UTC, merged