feat: subscriptions & related changes
Pycord-Development/pycord pull request #2564
Opened 2024-08-28 22:19 UTC by plun1331

## Summary

https://discord.com/developers/docs/change-log#premium-apps-entitlement-migration-and-new-subscription-api

## Information

- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-08-28 22:21 UTC, plun1331 commented
Untested (because i can't)

2024-08-28 22:33 UTC, Lulalaby commented on discord/enums.py
> +    inactive = 3
```suggestion
    active = 0
    ending = 1
    inactive = 2
```

2024-08-28 22:34 UTC, plun1331 commented on discord/enums.py
> +    inactive = 3
no; https://discord.com/developers/docs/resources/subscription#subscription-statuses

2024-08-28 22:35 UTC, Lulalaby commented
@plun1331 if u want to test it lmk, i have a few apps with monitization ready u could use

2024-09-19 18:32 UTC, plun1331 commented
tested

2024-09-22 01:01 UTC, JustaSqu1d requested changes

2024-09-22 01:01 UTC, JustaSqu1d commented on discord/monetization.py
> +            The user to retrieve subscriptions for.
```suggestion
            The user for which to retrieve subscriptions.
```
Sentences shouldn't end with a preposition

2024-09-22 01:01 UTC, JustaSqu1d commented on discord/iterators.py
> +            self._retrieve_subscriptions = self._retrieve_subscriptions_before_strategy  # type: ignore
elaborate on why type ignore is needed

2024-09-22 01:01 UTC, JustaSqu1d commented on discord/iterators.py
> +            self._retrieve_subscriptions = self._retrieve_subscriptions_after_strategy  # type: ignore
elaborate on why type ignore is needed

2024-09-22 01:01 UTC, JustaSqu1d commented on discord/iterators.py
> +            self._retrieve_subscriptions = self._retrieve_subscriptions_before_strategy  # type: ignore
elaborate on why type ignore is needed

2024-09-22 02:35 UTC, JustaSqu1d approved these changes

2024-09-26 18:57 UTC, plun1331 commented
@Lulalaby review when available please :3

2024-09-27 01:19 UTC, Lulalaby commented
i'm still down with illness

2024-12-12 19:14 UTC, DA-344 commented
This now requires the new changes from https://github.com/discord/discord-api-docs/pull/7304 , just a new field.

2024-12-12 19:25 UTC, Lulalaby commented
If you mean the country field, as noted by discord, it's only available through a private oauth scope. So I'm not sure if it's needed 😅

2024-12-12 19:27 UTC, DA-344 commented
I meant the ``renewal_sku_ids`` field 😅

2024-12-12 19:32 UTC, Lulalaby commented
Oop. Missed that. I only proof-read the discord pr 😅

2025-01-05 14:32 UTC, Dorukyum commented
@plun1331 update please.

2025-01-31 23:00 UTC, Lulalaby approved these changes

2025-01-31 23:00 UTC, merged