make FFmpegOpusAudio codec behave as docs suggest
Pycord-Development/pycord pull request #2581
Opened 2024-09-18 23:08 UTC by felix920506

## Summary

make FFmpegOpusAudio "codec" parameter behave as what the inline docs suggest

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-09-19 04:31 UTC, plun1331 commented
should we maybe change the docs instead because like, breaking changes and stuff

2024-09-19 10:52 UTC, felix920506 commented
This is my first contribution here so I don't really know if this would count as breaking or not. I checked the box only because it technically changes the behavior of this function.

2024-09-19 11:19 UTC, felix920506 commented
I don't think this is going to be much an issue since the only scenario it would break functionality on existing bots would be someone passing in "copy" for a source that isn't opus, which is something that was never supposed to work according to the docs. 
The fix this will require under that scenario would be a few lines at most (Likely single line changes for most cases.)

2024-09-20 05:44 UTC, felix920506 commented
I see this tagged with "changelog needed", is there anything that I need to do? If so are there instructions?

2024-09-20 05:58 UTC, JustaSqu1d commented
> I see this tagged with "changelog needed", is there anything that I need to do? If so are there instructions?

Here's an example of a changelog entry being added: https://github.com/Pycord-Development/pycord/pull/2577/commits/7fb1a4b07c1f4b2149a473f5287c0df2fa877474

2024-09-20 06:00 UTC, felix920506 commented
> > I see this tagged with "changelog needed", is there anything that I need to do? If so are there instructions?
> 
> 
> 
> Here's an example of a changelog entry being added: https://github.com/Pycord-Development/pycord/pull/2577/commits/7fb1a4b07c1f4b2149a473f5287c0df2fa877474

would this be "Fixed" or "Changed" ?

2024-09-20 11:36 UTC, Lulalaby commented
Fixed

2024-09-20 13:31 UTC, felix920506 commented
I have added an entry to the changelog.

2024-09-20 18:00 UTC, JustaSqu1d requested changes

2024-09-20 18:00 UTC, JustaSqu1d commented on discord/player.py
> +        # only re-encode ir source isn't already opus, else directly copy source audio stream
```suggestion
        # only re-encode if the source isn't already opus, else directly copy the source audio stream
```

2024-09-20 18:04 UTC, JustaSqu1d approved these changes

2024-09-20 19:12 UTC, merged