feat: Add function to get elapsed time of playing audio
Pycord-Development/pycord pull request #2587
Opened 2024-09-23 02:35 UTC by felix920506

## Summary

Adds a function to get the elapsed seconds of currently playing audio file

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-09-23 03:29 UTC, JustaSqu1d commented
Seconds seem really inflexible, what if we returned a `datetime.timedelta` object instead?

2024-09-23 03:48 UTC, felix920506 commented
Sounds reasonable

2024-09-28 04:46 UTC, felix920506 commented
Can I have a review on this?

2024-10-04 05:18 UTC, Dorukyum commented on discord/player.py
> +            self._played_frames += 1
Couldn't we utilise self.loops instead of creating another counter?

2024-10-05 01:00 UTC, felix920506 commented
Changed to use loops + an offset to keep track of when loops gets reset

2024-10-11 05:22 UTC, Dorukyum commented on discord/voice_client.py
> +        """Gets the elapsed time of the playing audio. Returns 0 if not playing anything."""
```suggestion
        """Returns the elapsed time of the playing audio."""
```

2024-10-11 05:32 UTC, Dorukyum requested changes
I find `client.elapsed()` to be clearer and simpler, what do you think?

2024-10-11 05:32 UTC, Dorukyum commented on CHANGELOG.md
> +  file. ([#2587](https://github.com/Pycord-Development/pycord/pull/2587/))
```suggestion
- Added `elapsed` method to `VoiceClient`.
  ([#2587](https://github.com/Pycord-Development/pycord/pull/2587/))
```

2024-10-11 05:32 UTC, Dorukyum commented on discord/voice_client.py
> +    def played_time(self) -> datetime.timedelta:
```suggestion
    def elapsed(self) -> datetime.timedelta:
```

2024-10-11 05:32 UTC, Dorukyum commented on discord/voice_client.py
> +            return datetime.timedelta()
```suggestion
        return datetime.timedelta()
```

2024-10-11 05:39 UTC, felix920506 commented
I don't have any preference between client.elapsed() or client.played_time()
If you think client.elapsed() is better then let's use that

2024-10-11 06:07 UTC, Dorukyum approved these changes

2024-10-11 08:59 UTC, Lulalaby approved these changes

2024-10-11 08:59 UTC, merged