feat: Add optional check parameter in utils.basic_autocomplete
Pycord-Development/pycord pull request #2590
Opened 2024-09-25 06:25 UTC by sweetbrulee

## Summary

Add optional ``check`` parameter in ``utils.basic_autocomplete``.

If ``check`` is provided with ``None``, a default check is used that includes items whose string representation starts with the user's input value, case-insensitive.

## Information

- [ ] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [X] I have searched the open pull requests for duplicates.
- [X] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-09-25 07:36 UTC, plun1331 reviewed
i don't think `check` is the right word for this, maybe `filter`?

2024-09-26 19:01 UTC, plun1331 commented on discord/utils.py
> +        the :class:`.AutocompleteContext` and an item from ``values``. If ``None`` is provided, a default filter is used that includes items whose string representation starts with the user's input v
add a versionadded thingy if possible

2024-09-26 20:28 UTC, JustaSqu1d requested changes

2024-09-26 21:43 UTC, plun1331 submitted a review, later dismissed

2024-09-26 21:50 UTC, JustaSqu1d requested changes

2024-09-26 21:50 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added optional `filter` parameter to `utils.basic_autocomplete`.
```suggestion
- Added optional `filter` parameter to `utils.basic_autocomplete()`.
```

2024-09-26 21:54 UTC, plun1331 approved these changes

2024-09-27 04:40 UTC, JustaSqu1d requested changes
Add a usage example in the example section of the function's doc string

2024-09-27 20:02 UTC, plun1331 approved these changes

2024-09-28 00:26 UTC, Lulalaby approved these changes

2024-09-28 00:26 UTC, merged