feat: message forwarding
Pycord-Development/pycord pull request #2598
Opened 2024-10-06 06:08 UTC by NeloBlivion

## Summary

Implements message forwarding, alongside some small cleanups for other message features.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-10-06 06:39 UTC, NeloBlivion commented
more or less done, just need to add mention/role mention handling... but still 403ing on my bot 😔

2024-10-06 08:55 UTC, Lulalaby commented
unlucky bcs its 95% out. you're in th holdout group. try making  new bot

2024-11-27 15:18 UTC, DA-344 commented on discord/message.py
> +        channel: Union[:class:`Emoji`, :class:`Reaction`, :class:`PartialEmoji`, :class:`str`]
Why is this ``Union[Emoji, Reaction, PartialEmoji, str]``...?

2025-01-05 14:38 UTC, Dorukyum commented
@NeloBlivion status?

2025-02-05 21:46 UTC, Lulalaby requested changes
one changelog please

2025-02-06 05:33 UTC, Lulalaby submitted a review, later dismissed

2025-02-06 06:41 UTC, Dorukyum requested changes
Testing required

2025-02-06 06:43 UTC, NeloBlivion commented
ah yeah, forgot to tick that box; as far as i've tested there haven't been any issues.

2025-02-10 11:21 UTC, Dorukyum submitted a review, later dismissed

2025-02-10 11:21 UTC, Dorukyum commented on discord/abc.py
> +                    utils.warn_deprecated(
Doesn't match the `InvalidArgument` error message below, also why?

2025-02-10 13:06 UTC, NeloBlivion commented on discord/abc.py
> +                    utils.warn_deprecated(
we discussed this when forwarding came out; before you could pass any `Message` into `reference` to automatically reply to it, but since forwarding was added this behaviour is too vague and should be removed in the next version.

2025-02-28 19:20 UTC, Lulalaby reviewed
whats the status here, can this be tested and merged?

2025-02-28 19:22 UTC, NeloBlivion commented
As far as I've tested it operates fine, would appreciate others testing if they may know of any edge cases/weird behaviour with the attributes of `ForwardedMessage` but otherwise it's feature complete.

2025-02-28 19:24 UTC, NeloBlivion commented
(Actually haven't done a full review of docs so maybe that'd be a good idea)

2025-03-01 15:40 UTC, DA-344 approved these changes
LGTM

2025-03-06 22:28 UTC, Paillat-dev approved these changes
IS there a particular reason this is not getting merged ? Or is this ok di per se ?

2025-03-07 04:03 UTC, JustaSqu1d submitted a review, later dismissed

2025-03-07 04:03 UTC, JustaSqu1d commented on discord/message.py
> +        The type of message reference. If this is not provided, assume default behavior (reply).
```suggestion
        The type of message reference. If this is not provided, assume the default behavior (i.e., reply).
```

2025-03-07 04:03 UTC, JustaSqu1d commented on discord/enums.py
> +    """The message reference's type"""
```suggestion
    """The type of the message reference object"""
```

2025-03-07 04:03 UTC, JustaSqu1d commented on discord/abc.py
> +            :meth:`~discord.Message.to_reference` or passed directly as a :class:`~discord.Message`. When replying, you can control
```suggestion
            A reference to the :class:`~discord.Message` you are replying to or forwarding, this can be created using
            :meth:`~discord.Message.to_reference` or passed directly as a :class:`~discord.Message`. When replying, you can control
```
Two things here
- this is a run-on sentence. Please reword and fix.
- "you" is too casual and the sentence should be reworded in passive voice.

2025-03-31 09:49 UTC, Paillat-dev commented
This pr should be marked as fixing 
- #2586

2025-03-31 09:51 UTC, Lulalaby commented
done but i still won't pay you

2025-05-17 13:09 UTC, NeloBlivion commented
pls merge this idk

2025-05-17 13:46 UTC, Lulalaby approved these changes

2025-05-17 13:47 UTC, merged

2025-05-17 13:47 UTC, Lulalaby commented
anything for u @NeloBlivion <3