chore: add support for Python 3.13
Pycord-Development/pycord pull request #2609
Opened 2024-10-15 11:36 UTC by timoo4devv

## Summary

## Information

- [ ] This PR fixes an issue.
- [x ] This PR adds something new (e.g. new method or parameters).
- [x ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ x] I have searched the open pull requests for duplicates.
- [x ] If code changes were made then they have been tested.
  - [x ] I have updated the documentation to reflect the changes.
- [x ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x ] I have updated the changelog to include these changes.

2024-10-15 12:14 UTC, Paillat-dev commented
Does the lib actually work in `3.13`? I believe some issues with voice need to be fixed first.

Either  #2176 is merged or `audioop-lts~=0.2.1` is added to req.

2024-10-15 14:03 UTC, Lulalaby approved these changes

2024-11-28 20:16 UTC, Paillat-dev commented
Pr should also update `README.rst` here:

https://github.com/Pycord-Development/pycord/blob/0f1a079836ccad8d7e1db917f9066414220def79/README.rst#L34

2024-12-03 18:56 UTC, Lulalaby requested changes

2024-12-03 18:56 UTC, Lulalaby commented on .readthedocs.yml
> +    python: "3.13"
Please do not touch readthedocs
This version is untested

2024-12-03 22:01 UTC, merged

2024-12-03 22:02 UTC, Lulalaby commented
We're gonna handle the rest internally for now.
There are still dependency issues so we can't merge it into main