refactor: add missing with_counts parameter to fetch_guilds method
Pycord-Development/pycord pull request #2615
Opened 2024-10-21 04:54 UTC by BruhDark

## Summary

This PR adds `with_counts` for the `fetch_guilds` method, which was missing.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-10-21 04:55 UTC, BruhDark commented
Side note 1: Blame my IDE for "fixing" spaces in other funcs in the files I edited.
Side note 2: Might wanna double check the edited documentation on such methods, don't know if it is correct.

2024-10-21 05:54 UTC, plun1331 reviewed
Changelog please :3 (under Added)

2024-10-21 09:31 UTC, Dorukyum requested changes

2024-10-21 09:31 UTC, Dorukyum commented on discord/client.py
> +        with_counts: Optional[:class:`bool`]
Shouldn't be None.
```suggestion
        with_counts: :class:`bool`
```

2024-10-21 09:31 UTC, Dorukyum commented on discord/iterators.py
> +    with_counts: Optional[:class:`bool`]
```suggestion
    with_counts: :class:`bool`
```

2024-10-21 17:02 UTC, BruhDark commented
Done

2024-10-21 17:33 UTC, plun1331 submitted a review, later dismissed

2024-10-25 18:08 UTC, JustaSqu1d requested changes

2024-10-25 18:08 UTC, JustaSqu1d commented on discord/client.py
> +            Whether to include count information in the guilds. This fills the
```suggestion
            Whether to include member count information in guilds. This fills the
```

2024-10-25 18:08 UTC, JustaSqu1d commented on discord/iterators.py
> +        Whether to include count information in the guilds. This fills the
```suggestion
        Whether to include member count information in guilds. This fills the
```

2024-10-25 22:17 UTC, BruhDark commented
Squid and his grammar.

2024-10-27 20:12 UTC, plun1331 approved these changes

2024-11-03 14:43 UTC, Dorukyum approved these changes

2024-11-03 15:48 UTC, plun1331 submitted a review, later dismissed

2024-11-03 15:51 UTC, plun1331 approved these changes

2024-11-03 15:52 UTC, merged