feat: Add helper methods to determine interactions integrations
Pycord-Development/pycord pull request #2659
Opened 2024-11-28 15:45 UTC by DA-344

## Summary

Adds ``Interaction.is_guild_integration`` and ``Interaction.is_user_integration`` to easily check whether an interaction has been invoked by a guild or user integration.

Also adds this to ``ApplicationContext``.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-11-28 16:03 UTC, Lulalaby submitted a review, later dismissed
Good addition! 💕🎉

2024-11-28 17:27 UTC, Paillat-dev approved these changes
👍

2024-12-10 07:37 UTC, JustaSqu1d requested changes
minor convention and grammar

2024-12-10 07:37 UTC, JustaSqu1d commented on discord/commands/context.py
> +
```suggestion
    def is_guild_integration(self) -> bool:
        """:class:`bool`: Checks if the invoked command is guild-installed.
        This is a shortcut for :meth:`Interaction.is_guild_integration`.

        .. versionadded:: 2.7
        """
        return self.interaction.is_guild_integration()

    def is_user_integration(self) -> bool:
        """:class:`bool`: Checks if the invoked command is user-installed.
        This is a shortcut for :meth:`Interaction.is_user_integration`.

        .. versionadded:: 2.7
        """
        return self.interaction.is_user_integration()

```

2024-12-10 07:37 UTC, JustaSqu1d commented on discord/interactions.py
> +
```suggestion
    def is_guild_integration(self) -> bool:
        """:class:`bool`: Checks if the interaction is a guild integration.

        .. versionadded:: 2.7
        """
        if self.guild_id:
            return self.authorizing_integration_owners.guild_id == self.guild_id
        return False

    def is_user_integration(self) -> bool:
        """:class:`bool`: Checks if the interaction is a user integration.

        .. versionadded:: 2.7
        """
        if self.user:
            return self.authorizing_integration_owners.user_id == self.user.id

        # This return should not be called but to make sure it returns the expected value
        return False

```

2024-12-10 07:37 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added helper methods to determine an `Interaction` integration type.
```suggestion
- Added helper methods to determine an `Interaction`'s integration type.
```

2024-12-10 07:55 UTC, JustaSqu1d requested changes
I don't quite like the naming. Interactions aren't exactly integrations.

Could we change it from `is_x_integration` to `is_x_authorized`?

2024-12-15 14:57 UTC, DA-344 commented
> I don't quite like the naming. Interactions aren't exactly integrations.

Yeah, but when invoking an application command, you are using an integration, which can either be guild or user installed.

> Could we change it from `is_x_integration` to `is_x_authorized`?
>
> Or if you have a better name that we could go with.

I think the current naming is nice, but if it is _really_ neccesary I can change it to ``is_x_authorized``.

2024-12-15 15:04 UTC, Paillat-dev commented
I feel like both namings make sense, maybe `is_x_authorized` is more explicit since that *is* in fact what is being checked.

2024-12-15 15:19 UTC, DA-344 commented
Makes sense, I have renamed the methods to ``is_x_authorised``, with its respective en-US aliases.

2024-12-15 23:35 UTC, JustaSqu1d commented on discord/commands/context.py
> +
Missing "There is an alias" note.

2024-12-15 23:36 UTC, JustaSqu1d requested changes

2024-12-15 23:36 UTC, JustaSqu1d commented on discord/commands/context.py
> +
Missing "There is an alias" note.

2024-12-17 23:54 UTC, JustaSqu1d requested changes

2024-12-17 23:54 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added helper methods to determine an `Interaction`'s integration type.
```suggestion
- Added helper methods to determine the integration type of an `Interaction`.
```

2024-12-17 23:54 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added helper methods to determine an `Interaction`'s integration type.
ambiguous punctuation

2024-12-25 20:27 UTC, plun1331 commented on CHANGELOG.md
> +- Added helper methods to determine the integration type of an `Interaction`.
```suggestion
- Added helper methods to determine the authorising party of an `Interaction`.
```

2024-12-26 18:26 UTC, plun1331 submitted a review, later dismissed

2024-12-27 08:39 UTC, JustaSqu1d requested changes
For some reason changelog is en-US.

2024-12-27 08:39 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Added helper methods to determine the authorising party of an `Interaction`.
```suggestion
- Added helper methods to determine the authorizing party of an `Interaction`.
```

2024-12-27 08:44 UTC, JustaSqu1d approved these changes

2024-12-27 16:02 UTC, Dorukyum approved these changes

2024-12-27 21:17 UTC, Lulalaby approved these changes
we really should stop doing american / british english

2024-12-27 21:17 UTC, merged