fix: :bug: Fix error when responding with paginator to an ephemeral deferred interaction
Pycord-Development/pycord pull request #2661
Opened 2024-11-28 20:51 UTC by Paillat-dev

## Summary
fix: #2173 

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

2024-12-17 23:53 UTC, JustaSqu1d requested changes

2024-12-17 23:53 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Fixed error when responding normally with a `Paginator` to an ephemerally deferred
```suggestion
- Fixed error when responding with a `Paginator` to an ephemerally deferred
```

2024-12-18 14:29 UTC, Paillat-dev commented on CHANGELOG.md
> +- Fixed error when responding normally with a `Paginator` to an ephemerally deferred
@JustaSqu1d Is it good like now ?

2024-12-18 15:06 UTC, JustaSqu1d commented on CHANGELOG.md
> +- Fixed error when responding normally with a `Paginator` to an ephemerally deferred
"Normally" seems redundant

2024-12-18 16:37 UTC, Paillat-dev commented on CHANGELOG.md
> +- Fixed error when responding normally with a `Paginator` to an ephemerally deferred
Yeah no I removed the normally.

2024-12-26 21:59 UTC, Paillat-dev commented on CHANGELOG.md
> +- Fixed error when responding normally with a `Paginator` to an ephemerally deferred
@JustaSqu1d ?

2024-12-26 22:06 UTC, JustaSqu1d approved these changes

2024-12-27 08:34 UTC, Dorukyum approved these changes

2024-12-27 08:37 UTC, merged