fix: Fixed Attachment Metadata Being Set Incorrectly In Interaction Responses
Pycord-Development/pycord pull request #2679
Opened 2024-12-27 00:42 UTC by Icebluewolf

## Summary
In interaction responses attachment metadata was being placed in the wrong spot in the request body causing discord to ignore it.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2024-12-27 08:29 UTC, plun1331 submitted a review, later dismissed

2024-12-27 08:37 UTC, JustaSqu1d requested changes
slightly ambiguous wording fix

2024-12-27 08:37 UTC, JustaSqu1d commented on CHANGELOG.md
> +  be ignored. ([#2679](https://github.com/Pycord-Development/pycord/pull/2679))
```suggestion
- Fixed attachment metadata being set incorrectly in interaction responses which caused it to
  be ignored. ([#2679](https://github.com/Pycord-Development/pycord/pull/2679))
```

2024-12-27 08:46 UTC, Dorukyum approved these changes
The wording is fine

2024-12-27 08:47 UTC, JustaSqu1d commented
> The wording is fine

It could be interpreted as the "interaction responses" being ignored as opposed to the "attachment metadata"

2024-12-27 15:58 UTC, Dorukyum commented
> > The wording is fine
> 
> 
> 
> It could be interpreted as the "interaction responses" being ignored as opposed to the "attachment metadata"

I hadn't realised that but your suggestion wouldn't solve it

2024-12-27 17:08 UTC, Icebluewolf commented on CHANGELOG.md
> +  be ignored. ([#2679](https://github.com/Pycord-Development/pycord/pull/2679))
Fixed with more clear wording of my own

2024-12-28 18:13 UTC, Icebluewolf commented
Don't merge yet

2024-12-28 18:51 UTC, Dorukyum requested changes

2024-12-28 18:51 UTC, Dorukyum commented on discord/webhook/async_.py
> +        payload["data"]["attachments"] = attachments
Potential `KeyError` as shown in #2682.

2024-12-28 19:24 UTC, Icebluewolf commented
Should Be Fixed
I tested
- Defer + Message
- Defer + Message With Attachment
- Message
- Message With Attachment

2024-12-28 20:15 UTC, Dorukyum approved these changes

2024-12-28 20:28 UTC, Lulalaby approved these changes
that looks better lmao

2024-12-28 20:29 UTC, merged