Support responding with deferred_channel_message to component interactions.
Pycord-Development/pycord pull request #309
Opened 2021-10-24 02:56 UTC by plun1331

## Summary

Allows users to choose between `deferred_channel_message` and `deferred_message_update` when responding to a component interaction.

![image](https://user-images.githubusercontent.com/49261529/138578440-3d06f172-8b74-4d9f-976d-c7268dc8a69d.png)

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, ...)

2021-10-30 21:43 UTC, Lulalaby requested changes
Why did you removed the new lines

2021-10-30 22:22 UTC, Middledot commented on discord/interactions.py
> +            raise discord.InteractionResponded(self._parent)
InteractionResponded is already imported

2021-10-30 22:22 UTC, Middledot commented on discord/interactions.py
> +            adapter = discord.webhook.async_.async_context.get()
async_context is already imported

2021-10-30 22:22 UTC, Middledot commented on discord/interactions.py
> +            defer_type = discord.InteractionResponseType.deferred_channel_message.value
InteractionType and InteractionResponseType are already imported

2021-11-01 17:23 UTC, Lulalaby commented
https://github.com/discord/discord-api-docs/pull/4035 < keep in mind

2021-11-02 14:57 UTC, BobDotCom commented on discord/interactions.py
> +            If ``True`` for interactions of type :attr:`InteractionType.component`, this will send an ephemeral 'bot is thinking' message in the channel.
```suggestion
            If ``True`` for interactions of type :attr:`InteractionType.component`, this will defer ephemerally.
```

2021-11-02 14:58 UTC, BobDotCom commented
Actually, could we just implement this into ctx.defer?

2021-11-02 15:02 UTC, Lulalaby commented
> 
> 
> Actually, could we just implement this into ctx.defer?

Would be better

2021-11-11 05:03 UTC, BobDotCom approved these changes

2021-11-11 05:07 UTC, Lulalaby approved these changes

2021-11-11 05:07 UTC, merged