Implement discord.utils.generate_snowflake
Pycord-Development/pycord pull request #336
Opened 2021-10-27 04:58 UTC by JDJGInc

2021-10-31 20:18 UTC, JDJGInc commented
should be working and good.

2021-11-01 19:39 UTC, Lulalaby approved these changes

2021-11-02 12:28 UTC, nerdguyahmad submitted a review, later dismissed

2021-11-02 14:59 UTC, BobDotCom requested changes
Merge conflicts here

2021-11-02 15:01 UTC, Lulalaby commented
> 
> 
> Merge conflicts here

Respöved

2021-11-02 15:03 UTC, BobDotCom approved these changes

2021-11-02 15:03 UTC, merged