Add AutocompleteContext for autocomplete callbacks
Pycord-Development/pycord pull request #361
Opened 2021-10-31 13:20 UTC by zeffo

## Summary

This PR adds AutocompleteContext. This context is passed to `Option.autocomplete`.

## Checklist

- [X] If code changes were made then they have been tested.
    - [X] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, ...)

2021-10-31 13:33 UTC, nerdguyahmad requested changes
Docs fixes, Ignore the syntax highlighting in suggestions. they seem broken or i don't know how to use them.

2021-10-31 13:33 UTC, nerdguyahmad commented on discord/commands/context.py
> +    """Represents a Discord autocomplete context.
```suggestion
    """Represents context for a slash command's option autocomplete.
```

2021-10-31 13:33 UTC, nerdguyahmad commented on discord/commands/context.py
> +        The names and values of all the options.
```suggestion
        A name to value mapping of the options that user has typed before this option.
```

2021-10-31 13:37 UTC, Lulalaby requested changes

2021-10-31 13:37 UTC, Lulalaby commented on discord/commands/context.py
> +        The names and values of all the options.
```suggestion
        A name to value mapping of the options that the user has selected before this option.
```

2021-10-31 15:49 UTC, zeffo commented
This should be slotted, no?

2021-10-31 15:58 UTC, nerdguyahmad commented
> This should be slotted, no?

Yes, it should be.

2021-10-31 16:07 UTC, Middledot commented on discord/commands/context.py
> +        self.options = options
```suggestion
        self.options = options

```

2021-10-31 16:21 UTC, zeffo commented
fuck i messed something up

2021-10-31 16:22 UTC, zeffo commented
can someone do black git magic and fix my shit, ty

2021-10-31 16:24 UTC, nerdguyahmad commented
Everything's fine.

2021-10-31 16:26 UTC, zeffo commented
![image](https://user-images.githubusercontent.com/43495198/139593113-4b106d02-75f7-4629-a672-43c80a7d18f3.png)
Are these supposed to be here

2021-11-01 06:15 UTC, Lulalaby commented
> ![image](https://user-images.githubusercontent.com/43495198/139593113-4b106d02-75f7-4629-a672-43c80a7d18f3.png)
> Are these supposed to be here

Yes because I committed it

2021-11-01 12:08 UTC, nerdguyahmad submitted a review, later dismissed

2021-11-01 12:10 UTC, Lulalaby approved these changes
LGTM

2021-11-02 14:46 UTC, BobDotCom commented on discord/commands/context.py
> +        self.options = options
```suggestion
        self.options = options

```

2021-11-02 14:55 UTC, BobDotCom requested changes
Please update utils.basic_autocomplete for this functionality

2021-11-03 09:56 UTC, CodeWithSwastik approved these changes

2021-11-03 09:57 UTC, merged