Fix for discord.User parsing
Pycord-Development/pycord pull request #398
Opened 2021-11-04 23:08 UTC by Apocryphon-X

## Summary

Closes #367. 
Fix for parsing of `discord.Member` / `discord.User` when Slash Command is invoked from a DM. 

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-05 21:38 UTC, BobDotCom requested changes

2021-11-05 21:38 UTC, BobDotCom commented on discord/commands/commands.py
> +
sync autocomplete callbacks are allowed now

2021-11-06 09:11 UTC, Lulalaby commented on discord/commands/commands.py
> +
oops, my fault, sry

2021-11-18 16:03 UTC, Dorukyum requested changes
Removing `ctx.` prefixes on lines 538 and 543 creates `NameError`s.

2021-12-03 19:59 UTC, Lulalaby commented
@Dorukyum

2021-12-08 15:20 UTC, Middledot approved these changes

2021-12-12 10:36 UTC, RPSMain approved these changes

2021-12-13 16:40 UTC, Dorukyum commented
Has this been extensively tested? Just to make sure.

2021-12-19 14:23 UTC, Dorukyum approved these changes

2021-12-19 14:23 UTC, merged