Added docstrings for the application command decorators
Pycord-Development/pycord pull request #412
Opened 2021-11-07 11:33 UTC by EnokiUN

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-07 20:27 UTC, FrostByte266 requested changes
In the numpy docstrings, the `Attributes` section is for class docstrings. When documenting methods, it should be `Parameters` instead

2021-11-07 20:41 UTC, EnokiUN commented
Done.

2021-11-07 21:15 UTC, FrostByte266 approved these changes

2021-11-08 16:39 UTC, Middledot approved these changes

2021-11-08 17:15 UTC, merged