baseholder implementation for timeouts
Pycord-Development/pycord pull request #441
Opened 2021-11-12 04:34 UTC by BobDotCom

## Summary

Implements timeouts

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-12 04:35 UTC, Dorukyum commented on discord/member.py
> +        'communication_disabled_until'
```suggestion
        'communication_disabled_until',
```

2021-11-23 00:57 UTC, Lulalaby requested changes

2021-11-23 00:57 UTC, Lulalaby commented on discord/member.py
> +        | communication_disabled_until | :attr:`Permissions.kick_members`     |
```suggestion
        | communication_disabled_until | :attr:`Permissions.manage_members`     |
```

2021-11-23 00:57 UTC, Lulalaby commented on discord/member.py
> +        You must have the :attr:`~Permissions.kick_members` permission to
```suggestion
        You must have the :attr:`~Permissions.manage_members` permission to
```

2021-11-23 00:57 UTC, Lulalaby commented on discord/member.py
> +        You must have the :attr:`~Permissions.kick_members` permission to
```suggestion
        You must have the :attr:`~Permissions.manage_members` permission to
```

2021-11-24 21:30 UTC, BobDotCom commented
Going to see if this needs any changes for the new timeout limits on the api

2021-11-24 21:31 UTC, BobDotCom commented
@Lulalaby your changes may have broken the table in the last commit.

2021-11-25 01:41 UTC, Lulalaby commented
Which table

2021-11-25 01:41 UTC, Lulalaby commented
Oh

2021-11-25 01:42 UTC, Lulalaby requested changes

2021-11-25 01:42 UTC, Lulalaby commented on discord/member.py
> +        | communication_disabled_until | :attr:`Permissions.manage_members`     |
```suggestion
        | communication_disabled_until | :attr:`Permissions.manage_members`   |
```

2021-11-25 01:43 UTC, Lulalaby commented
Fixed 😘

2021-11-26 14:53 UTC, Lulalaby commented
Timeouts are now locked to staff

2021-12-01 22:02 UTC, BobDotCom commented
> Timeouts are now locked to staff

Timeouts have now been unlocked and enabled on all Partner and DMD servers.

2021-12-10 14:57 UTC, Dorukyum approved these changes

2021-12-12 10:39 UTC, RPSMain approved these changes

2021-12-18 11:14 UTC, Lulalaby approved these changes

2021-12-18 11:15 UTC, merged