Remove ids and grammar changes.
Pycord-Development/pycord pull request #470
Opened 2021-11-17 22:18 UTC by capslock321

## Summary
# IDS
Specific IDS was in the example files. Those who just want to try the program will be faced with discord.Forbidden if they forget to change the IDS. This fixes this minor inconvenience by removing the IDS. 
# Grammar
There are specific comments that are lacking periods or are just grammatically incorrect. Although comments do not have to have capitalization and periods, it is best to add them to bring forth a sense of professionalism.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-17 22:35 UTC, Lulalaby commented on examples/views/button_roles.py
> +
```suggestion

```

2021-11-17 22:35 UTC, Lulalaby approved these changes

2021-11-18 12:54 UTC, Dorukyum reviewed
I think it's better to use `...` to show that people should add values.

2021-11-18 12:54 UTC, Dorukyum commented on examples/views/button_roles.py
> +
```suggestion
    ...
```

2021-11-18 12:54 UTC, Dorukyum commented on examples/views/button_roles.py
> +    @slash_command(guild_ids=[], description="Post the button role message")
```suggestion
    @slash_command(guild_ids=[...], description="Post the button role message")
```

2021-11-18 12:54 UTC, Dorukyum commented on examples/views/button_roles.py
> +        guild = self.bot.get_guild()
```suggestion
        guild = self.bot.get_guild(...)
```

2021-11-27 18:31 UTC, Lulalaby approved these changes

2021-11-30 06:46 UTC, RPSMain requested changes

2021-11-30 06:46 UTC, RPSMain commented on examples/views/button_roles.py
> +            The interaction object that was created when the user clicked on the button.
```suggestion
            The interaction object that was created when a user clicks on a button.
```

2021-12-12 10:35 UTC, RPSMain approved these changes

2021-12-12 10:35 UTC, merged