Add More examples
Pycord-Development/pycord pull request #484
Opened 2021-11-22 12:59 UTC by ResetXD

#248 
interactions for cogs with better examples

2021-11-22 13:04 UTC, Lulalaby requested changes
And class names maybe camel case

2021-11-22 13:04 UTC, Lulalaby commented on examples/interactionsBot/cogs/slashGroup_cog.py
> +        client.add_application_command(moderation)
More documentation for user

2021-11-22 13:04 UTC, Lulalaby commented on examples/interactionsBot/cogs/button_cog.py
> +        ctx.mememsg = mememsg
More documentation for user

2021-11-22 13:04 UTC, Lulalaby commented on examples/interactionsBot/cogs/button_cog.py
> +    }
More documentation for user

2021-11-22 13:04 UTC, Lulalaby commented
But anyway, thanks!

2021-11-22 13:22 UTC, ResetXD commented
@Lulalaby updated with more documentation please review and tell if it needs any changes

2021-11-22 13:36 UTC, Lulalaby submitted a review, later dismissed

2021-11-22 15:37 UTC, ResetXD commented
> The cog loading should also be static, not os.listdir() since many people consider that to not be a good standard practice.

this have became the more "go-to" way of importing cogs nowerdays.

and the examples highlights all of the interactions possible in pycord.

> It would be much more effective to simply show a simple example of a cog, maybe with one of each type of application command. 
i personally feel that simple examples wont help the user understand the complex part of the interaction.

@BobDotCom

2021-11-22 16:19 UTC, nerdguyahmad commented
As Bob mentioned above, I agree with that, This example does way too much stuff and is too vague. Examples are meant to just provide a very basic overview to users to give them a quickstart.

2021-11-22 16:40 UTC, ResetXD commented
@nerdguyahmad @BobDotCom check and tell if it needs further revision

2021-11-22 20:44 UTC, BobDotCom commented
I still feel like these examples are far too advanced. For an example showcasing usage of cogs, I feel it would make sense to simply have one cog, with one or two slash commands, and one of each type of context menu. It probably shouldn't even have components, since those aren't particularly affected by using cogs.

2021-11-22 20:58 UTC, Lulalaby commented
> I still feel like these examples are far too advanced. For an example showcasing usage of cogs, I feel it would make sense to simply have one cog, with one or two slash commands, and one of each type of context menu. It probably shouldn't even have components, since those aren't particularly affected by using cogs.

Agreeing with that.
Advanced examples should be covered in external sources.

2021-11-23 01:35 UTC, nerdguyahmad commented
^ that

2021-11-23 02:35 UTC, ResetXD commented
alr i will try to further simplify the examples.

2021-11-23 03:02 UTC, ResetXD commented
@Lulalaby @BobDotCom @nerdguyahmad

2021-11-23 11:21 UTC, Lulalaby commented
@ResetXD please fix the code spell error https://github.com/Pycord-Development/pycord/runs/4294735196?check_suite_focus=true

2021-11-23 11:23 UTC, ResetXD commented
@Lulalaby

2021-11-29 08:54 UTC, ResetXD commented
@Lulalaby i found a way better to manage SlashCommandGroup in cogs or somewhat cogs i will implement that before

2021-11-29 09:29 UTC, ResetXD commented
check and tell, i tested the code and it works fine.

2021-11-29 14:43 UTC, BobDotCom commented
> @Lulalaby i found a way better to manage SlashCommandGroup in cogs or somewhat cogs i will implement that before

#462 will rework groups. Let's wait until that is merged and use the new syntax.

2021-11-30 06:41 UTC, RPSMain requested changes
should've gotten then all

2021-11-30 08:08 UTC, ResetXD commented on examples/interactionsBot/cogs/slashOption_cog.py
> +    async def av_error(self, ctx:Context ,error):
unnecessary

2021-11-30 08:08 UTC, ResetXD commented on examples/interactionsBot/cogs/slashGroup_cog.py
> +        async def ban(self, ctx:Context,
unnecessary

2021-11-30 08:09 UTC, ResetXD commented on examples/interactionsBot/cogs/slashOption_cog.py
> +    async def av(self,ctx,
unnecessary

2021-11-30 08:15 UTC, ResetXD commented
@RPSMain replacing client with bot is not useful so why a change request.
many people uses client, few people also uses bot as the variable so why the change.

2021-11-30 08:16 UTC, RPSMain commented on examples/interactionsBot/cogs/slashGroup_cog.py
> +        async def ban(self, ctx:Context,
it is? it makes the examples follow pep8

2021-11-30 08:17 UTC, RPSMain commented
> @RPSMain replacing client with bot is not useful so why a change request. many people uses client, few people also uses bot as the variable so why the change.

Consistency you are subclassing Bot so it should be Bot not Client.

2021-11-30 08:17 UTC, ResetXD commented
also a space before ctx or any other function argument is irrelevant to pep 8

2021-11-30 08:22 UTC, RPSMain commented
> also a space before ctx or any other function argument is irrelevant to pep 8

https://www.python.org/dev/peps/pep-0008/#variable-annotations

2021-11-30 08:23 UTC, ResetXD commented
> Consistency you are subclassing Bot so it should be Bot not Client.

what about the file name, **bot.py** shouldn't it be called **main.py** then.

2021-11-30 08:25 UTC, RPSMain commented
> what about the file name, **bot.py** shouldn't it be called **main.py** then.

if you want to.

2021-11-30 08:27 UTC, ResetXD commented
> if you want to.

alr will fix all again ig.

2021-11-30 13:12 UTC, RPSMain commented
@ResetXD have you linted the examples?

2021-11-30 13:52 UTC, Lulalaby commented
> replacing client with bot is not useful so why a change request.

We don't support self-botting, which would be client. 
So for this purpose bot is better.

2021-12-01 13:32 UTC, BobDotCom commented
> > replacing client with bot is not useful so why a change request.
> 
> We don't support self-botting, which would be client. 
> So for this purpose bot is better.

Client is used for bots, just not for slash commands.

2021-12-01 13:47 UTC, Lulalaby approved these changes

2021-12-03 02:30 UTC, RPSMain commented
@ResetXD this should fix the errrors https://github.com/ResetXD/pycord/pull/1

2021-12-03 09:15 UTC, RPSMain approved these changes

2021-12-19 21:35 UTC, merged