Update button_roles.py
Pycord-Development/pycord pull request #493
Opened 2021-11-23 18:25 UTC by SpeedLight-Dev

The changes include better code explanation and the code has been rendered to be more generalized.

2021-11-23 18:32 UTC, Lulalaby approved these changes

2021-11-23 18:53 UTC, Tommins-IT approved these changes

2021-11-23 18:54 UTC, Lulalaby commented
Fix the codespell error please @SpeedLight-Dev

2021-11-23 19:28 UTC, SpeedLight-Dev commented
> Fix the codespell error please @SpeedLight-Dev

Done!

2021-11-23 19:43 UTC, Lulalaby approved these changes

2021-11-24 15:01 UTC, ChickenDevs requested changes
Anywhere you removed id(s), we should put in `...` to show the end user where to put their ids.

2021-11-24 16:08 UTC, SpeedLight-Dev commented
> Anywhere you removed id(s), we should put in `...` to show the end user where to put their ids.

Ok, I'll do it right now! :)

2021-11-24 16:11 UTC, Lulalaby approved these changes

2021-11-24 19:42 UTC, BobDotCom requested changes

2021-11-24 19:42 UTC, BobDotCom commented on examples/views/button_roles.py
> +# This list will contain role IDs that will be added as buttons split by a comma ",".
```suggestion
# This list will contain role IDs that will be added as buttons.
```
Shouldn't need to specify the comma part.

2021-11-24 19:42 UTC, BobDotCom commented on examples/views/button_roles.py
> +        This function will be called any time a user clicks on this button
```suggestion
        """This function will be called any time a user clicks on this button
```
consistency with project code style

2021-11-24 19:42 UTC, BobDotCom commented on examples/views/button_roles.py
>              The interaction object that was created when the user clicked on the button
Could we just remove this from the docstring? Doesn't feel like we need docs for examples.

2021-11-24 19:42 UTC, BobDotCom commented on examples/views/button_roles.py
> +        Slash command to post a new view with a button for each role
```suggestion
        """Slash command to post a new view with a button for each role
```
Consistency with project code style.

2021-11-24 19:42 UTC, BobDotCom commented on examples/views/button_roles.py
> +        This function is called every time the bot restarts.
```suggestion
        """This function is called every time the bot restarts.
```
Consistency with project code style.

2021-11-25 22:47 UTC, SpeedLight-Dev commented
I should have done everything you requested.

2021-11-25 22:50 UTC, closed without merging

2021-11-25 22:50 UTC, SpeedLight-Dev commented
Gonna open a new one better.