Add autocomplete example
Pycord-Development/pycord pull request #503
Opened 2021-11-24 23:20 UTC by krittick

## Summary

**Note: Example works but PR is still a work in progress to polish things, add comments, etc.**

Adds an autocomplete example that demonstrates both basic usage, and usage of the `AutocompleteContext.options` parameter.

Closes #487 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue. (feature request)
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change  - new example

2021-11-25 01:02 UTC, krittick commented
Could probably use some work on the comments/docstrings for the example, though I tried to make it clear which concepts are being demonstrated.

2021-11-25 01:50 UTC, Lulalaby reviewed
I like that! Thanks.

Not gonna approve it tho because I'm unsure about the variable naming.

2021-11-25 03:24 UTC, BobDotCom requested changes
Maybe assign BASIC_ALLOWED and other config lists to bot.basic_allowed, etc.

2021-11-25 03:24 UTC, BobDotCom commented on examples/app_commands/slash_autocomplete.py
> +@slash_command(name="ac_example", guild_ids=[...])
```suggestion
@bot.slash_command(name="ac_example")
```

2021-11-25 03:24 UTC, BobDotCom commented on examples/app_commands/slash_autocomplete.py
> +@slash_command(name="ac_basic_example", guild_ids=[...])
```suggestion
@bot.slash_command(name="ac_basic_example")
```

2021-11-25 03:39 UTC, krittick commented
> Maybe assign BASIC_ALLOWED and other config lists to bot.basic_allowed, etc.

I actually do this in my own bot and agree it's a best practice, but I figured that keeping things simple for this example would be best to keep the focus on the autocomplete functionality itself. It's easy enough (or should be) for bot developers to know to store those as class variables, etc. where appropriate.

2021-11-25 03:43 UTC, Lulalaby commented
> I figured that keeping things simple for this example would be best to keep the focus on the autocomplete functionality itself

Agreeing with that

2021-11-26 03:25 UTC, BobDotCom approved these changes

2021-11-26 03:27 UTC, RPSMain approved these changes

2021-11-26 04:49 UTC, Lulalaby approved these changes

2021-11-26 04:49 UTC, merged