Add description to Attachments and Files
Pycord-Development/pycord pull request #509
Opened 2021-11-25 19:53 UTC by plun1331

## Summary

Adds the `description` attribute to `Attachment` and `File`

@zeffo helped with implementing file sending.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-25 20:33 UTC, plun1331 commented
Tried to add to interaction message edits but after a half hour couldn't figure out what i was doing

2021-11-26 04:57 UTC, Lulalaby commented
> Tried to add to interaction message edits but after a half hour couldn't figure out what i was doing

Interactions seems to be broken for descriptions

2021-11-29 15:22 UTC, BobDotCom requested changes
Why is single file support removed from this?

2021-11-29 15:30 UTC, Lulalaby commented on discord/message.py
> +                # don't want it to remove any attachments when we just add a new file
This btw.

2021-11-29 23:26 UTC, plun1331 commented on discord/message.py
> +                # don't want it to remove any attachments when we just add a new file
You can still remove files the same way, this just makes is so if you don't explicitly pass in attachments then it won't remove them.

2021-11-30 06:51 UTC, RPSMain requested changes

2021-11-30 06:51 UTC, RPSMain commented on discord/file.py
> +        A description of the file, used by Discord to display alt text on images.
```suggestion
        The description of a file, used by Discord to display alternative text on images.
```

2021-11-30 06:51 UTC, RPSMain commented on discord/interactions.py
> +
```suggestion

```

2021-11-30 13:59 UTC, BobDotCom commented on discord/message.py
> +                # don't want it to remove any attachments when we just add a new file
The ideal functionality would be:
```py
m = await send("hi", file=x)  # Sends with file x
await m.edit("hello")  # Leaves file x
await m.edit(files=m.attachments+[y])  # Adds file y
await m.edit(files=[y])  # Removes file x
await m.edit(files=[])  # Removes files
```
I'm not able to read through all your code again at the moment. Does your code function in this way?

2021-11-30 23:34 UTC, plun1331 commented on discord/message.py
> +                # don't want it to remove any attachments when we just add a new file
The usage should look like this:
```py
m = await send("hi", file=x)  # Sends with file x
await m.edit("hello")  # Leaves file x
await m.edit(files=[y])  # Adds file y
await m.edit(attachments=[y])  # Removes file x, y here would be a discord.Attachment
await m.edit(attachments=[])  # Removes files
```

Here's the code I actually used for testing:
```py
msg = await message.reply('a', files=[
    discord.File('banner.jpg', description='Profile banner'), # banner 1
    discord.File('banner.jpg', description='Profile banner 2') # banner 2
]) # sends message with 2 attachments
await asyncio.sleep(3)
msg = await message.edit('e') # leaves both attachments
file = discord.File('banner.jpg', description='Profile banner 3') # banner 3
attachment = msg.attachments[0] 
await asyncio.sleep(3)
await msg.edit(file=file, attachments=[attachment]) # adds banner 3, removes banner 2
```

I tried to keep the existing behavior of `edit`, where `attachments` is used to specify what files to keep, and `files` is used to add new files.

2021-12-12 10:41 UTC, RPSMain approved these changes

2021-12-22 12:04 UTC, Lulalaby approved these changes

2022-01-01 00:11 UTC, ChickenDevs approved these changes

2022-01-01 00:14 UTC, merged