Update button_roles.py
Pycord-Development/pycord pull request #510
Opened 2021-11-25 22:54 UTC by SpeedLight-Dev

In this new version of the file, the sample IDs have been removed so that people do not come and ask the server why the code is giving an error (which often happens in new developers who copy and paste the codes).

2021-11-26 14:55 UTC, Lulalaby requested changes

2021-11-26 14:55 UTC, Lulalaby commented on examples/views/button_roles.py
> +role_ids = [ ]
```suggestion
role_ids = [ ... ]
```

2021-11-26 14:55 UTC, Lulalaby commented on examples/views/button_roles.py
> +    @slash_command(guild_ids=[], description="Post the button role message")
```suggestion
    @slash_command(guild_ids=[ ... ], description="Post the button role message")
```

2021-11-26 14:55 UTC, Lulalaby requested changes

2021-11-26 14:55 UTC, Lulalaby commented on examples/views/button_roles.py
> +        guild = self.bot.get_guild()
```suggestion
        guild = self.bot.get_guild( ... )
```

2021-11-27 17:13 UTC, Lulalaby approved these changes

2021-11-27 17:14 UTC, Middledot approved these changes

2021-11-27 17:14 UTC, merged