Add new `Thread.archive`
Pycord-Development/pycord pull request #518
Opened 2021-11-29 18:39 UTC by Sengolda

## Summary
Adds a new Thread.archive method that archives a thread.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-11-30 05:40 UTC, RPSMain requested changes

2021-11-30 05:40 UTC, RPSMain commented on discord/threads.py
> +        Used to archive a thread, this is an alias to using :meth:`Thread.edit` to archive a thread.
```suggestion
        Used to archive a thread, aliases :meth:`Thread.edit` to archive a thread.
```

2021-11-30 05:40 UTC, RPSMain commented on discord/threads.py
> +            The thread that you have just archived.
```suggestion
            The thread that you have archived.
```

2021-11-30 08:32 UTC, Dorukyum requested changes
There are some wording inconsistencies. See the docstring for `Thread.edit`.

2021-12-02 14:51 UTC, nerdguyahmad requested changes

2021-12-02 14:51 UTC, nerdguyahmad commented on discord/threads.py
> +        Used to archive a thread, aliases :meth:`Thread.edit` to archive a thread.
```suggestion
        Archives the thread. This is a shorthand of :meth:`.edit`.
```

2021-12-02 14:51 UTC, nerdguyahmad commented on discord/threads.py
> +            When set to True it will lock the thread. This will default to False.
```suggestion
            Whether to lock the thread on archive, Defaults to False.
```

2021-12-02 14:51 UTC, nerdguyahmad commented on discord/threads.py
> +            The thread that you have archived.
```suggestion
            The updated thread.
```

2021-12-12 10:43 UTC, VincentRPS submitted a review, later dismissed

2021-12-19 00:36 UTC, Lulalaby requested changes

2021-12-19 00:36 UTC, Lulalaby commented on discord/threads.py
> +
```suggestion
```

2021-12-19 00:36 UTC, Lulalaby commented on discord/threads.py
> +    async def archive(self, locked: bool = MISSING) -> Thread:
Add a unarchive function maybe?

2021-12-20 17:32 UTC, Lulalaby commented on discord/threads.py
> +    async def unarchive(self, locked: bool = MISSING) -> Thread:
remove locked :)

2021-12-21 10:47 UTC, Lulalaby submitted a review, later dismissed

2021-12-21 10:49 UTC, Dorukyum requested changes

2021-12-21 10:49 UTC, Dorukyum commented on discord/threads.py
> +        :class:`Thread`
```suggestion
        :class:`.Thread`
```

2021-12-21 10:49 UTC, Dorukyum commented on discord/threads.py
> +        :class:`Thread`
```suggestion
        :class:`.Thread`
```

2021-12-21 11:02 UTC, Lulalaby submitted a review, later dismissed

2021-12-29 07:52 UTC, Dorukyum approved these changes

2021-12-29 07:53 UTC, Lulalaby approved these changes

2021-12-29 07:53 UTC, merged