Rename Permission to CommandPermission
Pycord-Development/pycord pull request #543
Opened 2021-12-05 03:08 UTC by TheReaper62

## Summary

Rename Permission to CommandPermission as per [Issue#416](https://github.com/Pycord-Development/pycord/issues/416)

## Checklist

- [ ] This PR fixes an issue.

2021-12-05 03:35 UTC, RPSMain commented
by the way "as per" isn't a [issue keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

2021-12-09 16:35 UTC, BobDotCom requested changes

2021-12-09 16:35 UTC, BobDotCom commented on discord/commands/commands.py
> +        kwargs.pop("guild_ids", None)
```suggestion
        self.guild_ids: Optional[List[int]] = kwargs.pop("guild_ids", None)
```

2021-12-22 12:05 UTC, Lulalaby approved these changes

2021-12-27 07:34 UTC, TheReaper62 commented
Stale PR

2021-12-29 11:29 UTC, Lulalaby commented
Closing as stale. Follow-up: #662

2021-12-29 11:29 UTC, closed without merging