Making A CODEOWNERS
Pycord-Development/pycord pull request #547
Opened 2021-12-07 06:04 UTC by RPSMain

## Summary

havent fully finished it but codeowners!
They will be automatically asked for review and either @CodeWithSwastik or @BobDotCom can
require reviews from codeowners in branch protection i they want to

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-12-07 06:04 UTC, RPSMain commented on .github/CODEOWNERS
> +/docs/ @RPSMain
gonna have to search for other people who have committed a-lot

2021-12-07 17:06 UTC, Lulalaby approved these changes

2021-12-08 07:03 UTC, nerdguyahmad requested changes

2021-12-08 07:03 UTC, nerdguyahmad commented on .github/CODEOWNERS
> +/discord/welcome_screen.py @nerdguyahmed @Prince2347X @Middledot
everyone uses "e" in my name for some reason, but it's "a"

2021-12-08 07:34 UTC, nerdguyahmad submitted a review, later dismissed

2021-12-08 07:38 UTC, Lulalaby approved these changes

2021-12-12 21:08 UTC, Lulalaby approved these changes

2021-12-22 16:21 UTC, Middledot approved these changes

2021-12-22 16:32 UTC, merged

2021-12-22 23:30 UTC, BobDotCom commented
Reverted. Please open a new PR for further discussion