Add timeout example
Pycord-Development/pycord pull request #613
Opened 2021-12-22 15:03 UTC by Dorukyum

## Checklist
- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-12-22 15:06 UTC, HyperGH commented
Shouldn't it be `datetime.datetime.now(datetime.timezone.utc)` or `discord.utils.utcnow()`? Otherwise it may not be timezone aware.

2021-12-22 19:35 UTC, BobDotCom submitted a review, later dismissed
Please add an example of the new method I'm adding (momentarily in a pull request)

2021-12-25 01:59 UTC, HyperGH requested changes
datetime.datetime.utcnow() still produces a naive-datetime, for this to be timezone-aware, please see my suggestions.

2021-12-26 16:05 UTC, Lulalaby approved these changes

2022-01-01 00:00 UTC, ChickenDevs approved these changes

2022-01-01 00:01 UTC, merged