Add a timeout_for method
Pycord-Development/pycord pull request #619
Opened 2021-12-22 20:32 UTC by BobDotCom

## Summary

Adds a timeout_for method to timeout members for an amount of time instead of until a set date. *Untested*

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-12-23 20:37 UTC, Lulalaby approved these changes

2021-12-24 18:48 UTC, Dorukyum requested changes

2021-12-24 18:48 UTC, Dorukyum commented on discord/member.py
> +        You must have the :attr:`~Permissions.moderate_members` permission to  timeout a member.
Double spaces
```suggestion
        You must have the :attr:`~Permissions.moderate_members` permission to timeout a member.
```

2021-12-24 18:54 UTC, ChickenDevs approved these changes

2021-12-24 18:55 UTC, Dorukyum approved these changes

2021-12-24 18:55 UTC, merged