Global commands will be sent to Discord to register only if it differs from the existing global commands from Discord's servers
Pycord-Development/pycord pull request #634
Opened 2021-12-24 04:25 UTC by PenguinDevs

## Summary

The method `.register_commands()` in the bot.py file of the current version of Pycord always deploy the global slash commands every time the bot is started. This method is not ideal because it is telling Discord to roll out the commands every single time the bot is started when the global slash commands may not differ from the previous deployment of the commands. This method leads therefore leads to the `Invalid interaction application command` that will occur every single start of the bot for up to one hour. During this period when all global slash commands in the bot will always return `Invalid interaction application command` rendering it to be unusable by the user.

This pull aims to fix the `Invalid interaction application command` by using the `.register_commands()` method to only deploy the global slash commands using the `http.bulk_upsert_global_commands()` method only if the global commands stored in Discord from `http.get_global_commands()` has certain attributes that differs from the global commands (no guild_ids) in `.pending_application_commands`. This means that if the global commands are not changed in the bot's code by comparing to the last deployment of global commands to Discord, users will not receive the `Invalid interaction application command`. `Invalid interaction application command` will only occur if the global commands have changed when the bot is started and Discord is still attempting to roll out the global commands taking up to an hour using the new deployment of global commands.

## Checklist

- [x] If code changes were made then they have been tested (only for global slash commands).
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-12-24 04:31 UTC, VincentRPS submitted a review, later dismissed

2021-12-24 13:09 UTC, Lulalaby commented
Good job
![anime-approve](https://user-images.githubusercontent.com/14029133/147354991-436a504f-54ff-4a3d-9407-e62a3b5b0a62.gif)

2021-12-24 16:21 UTC, BobDotCom requested changes
Please see the suggestions I made on this. In addition, I will work on further improving command registration soon. Partially completes #433.

2021-12-24 16:21 UTC, BobDotCom commented on discord/bot.py
> +                                    print(f"A change in the '{key2_change}' property of '{key}' in the '{command.name}' global command was noticed, will send to Discord to update")
We should probably send this to `logging.info` or else not log it at all. No need to print this.
```suggestion
                                    logging.info(f"A change in the '{key2_change}' property of '{key}' in the '{command.name}' global command was noticed, will send to Discord to update")
```

2021-12-24 16:21 UTC, BobDotCom commented on discord/bot.py
> +                                print(f"A change in the '{key}' property of '{command.name}' global command was noticed, will send to Discord to update")
We should probably send this to `logging.info` or else not log it at all. No need to print this.
```suggestion
                                logging.info(f"A change in the '{key}' property of '{command.name}' global command was noticed, will send to Discord to update")
```

2021-12-24 16:21 UTC, BobDotCom commented on discord/bot.py
> +                    print(f"A registered global command '{name}' is not found in the pending global commands, will send to Discord to update")
We should probably send this to `logging.info` or else not log it at all. No need to print this.
```suggestion
                    logging.info(f"A registered global command '{name}' is not found in the pending global commands, will send to Discord to update")
```

2021-12-24 16:21 UTC, BobDotCom commented on discord/bot.py
> +                    print(f"A pending global command '{command.name}' is not registered in Discord servers, will send to Discord to update")
We should probably send this to `logging.info` or else not log it at all. No need to print this.
```suggestion
                    logging.info(f"A pending global command '{command.name}' is not registered in Discord servers, will send to Discord to update")
```

2021-12-26 19:46 UTC, BobDotCom approved these changes

2021-12-26 19:49 UTC, Lulalaby approved these changes

2021-12-26 19:50 UTC, merged