Cooldowns and max concurrency for application commands
Pycord-Development/pycord pull request #674
Opened 2021-12-31 16:14 UTC by Dorukyum

## Summary
A replacement for #458 that doesn't move cooldowns out of ext.commands.
Also allows using max concurrency with application commands.
Tested with a guild user command and a guild slash command.
Closes #266.

## Checklist
- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

2021-12-31 23:53 UTC, ChickenDevs submitted a review, later dismissed
need to fix "non-existent" spelling in comments, other than that, LGTM

2021-12-31 23:58 UTC, Lulalaby requested changes

2021-12-31 23:58 UTC, Lulalaby commented on discord/commands/commands.py
> +            bucket = self._buckets.get_bucket(ctx, current)  # type: ignore (ctx instead of non-existant message)
```suggestion
            bucket = self._buckets.get_bucket(ctx, current)  # type: ignore (ctx instead of non-existent message)
```

2021-12-31 23:58 UTC, Lulalaby commented on discord/commands/commands.py
> +                await self._max_concurrency.release(ctx)  # type: ignore (ctx instead of non-existant message)
```suggestion
                await self._max_concurrency.release(ctx)  # type: ignore (ctx instead of non-existent message)
```

2021-12-31 23:58 UTC, Lulalaby commented on discord/commands/commands.py
> +            await self._max_concurrency.acquire(ctx)  # type: ignore (ctx instead of non-existant message)
```suggestion
            await self._max_concurrency.acquire(ctx)  # type: ignore (ctx instead of non-existent message)
```

2021-12-31 23:58 UTC, Lulalaby commented on discord/commands/commands.py
> +            bucket = self._buckets.get_bucket(ctx)  # type: ignore (ctx instead of non-existant message)
```suggestion
            bucket = self._buckets.get_bucket(ctx)  # type: ignore (ctx instead of non-existent message)
```

2021-12-31 23:59 UTC, Lulalaby approved these changes

2022-01-01 00:15 UTC, ChickenDevs approved these changes

2022-01-01 00:19 UTC, merged