Avatar command example
Pycord-Development/pycord pull request #73
Opened 2021-09-02 14:13 UTC by Rxann

## Summary

This adds an avatar slash commands to the examples/app_commands/slash_basic.py file. This is a small change but I feel people can use it and learn from it. This is my first pull request so if I messed up the checklist, I am sorry

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-09-02 15:39 UTC, jgayfer reviewed
Congrats and thank you for your first PR!

Though I'm not sure how much value this example provides over the ones we already have.

2021-09-02 15:54 UTC, zeffo requested changes
There are a few changes which I think would be nice:
1) use `member = member or ctx.author`
2) pass `member.avatar.url` directly to `embed.set_image` 
3) format the code with black so it looks good

```py
@bot.slash_command(guild_ids=[489635674987692042])
async def avatar(ctx, member: discord.Member = None):
    """Sends the mentioned user's or author's avatar"""

    member = (
        member or ctx.author
    )  # If no one is passed in for the member argument, it will make the author the member.

    embed = discord.Embed(title=f"{member}'s avatar", color=discord.Color.blurple())
    embed.set_image(url=member.avatar.url)

    await ctx.send(
        embed=embed
    )  # This will send the mentioned user or the authors avatar in an embed!
``` 
Just a suggestion.

2021-09-02 15:57 UTC, Astrea49 commented
Just another addition: shouldn't you use `display_avatar` over `avatar`? That way, a user can get their guild avatar if they have one (and it'll automatically get their normal avatar if they don't).

2021-09-02 16:10 UTC, Rxann commented
Thank you everyone for all of the feedback!! I just committed the changes

2021-09-02 16:13 UTC, Rxann commented
If anyone has any ideas for more examples, you can ping me in the discord or mention me in a feature request issue!

2021-09-03 13:28 UTC, Dorukyum commented
Can you format the code?

2021-09-03 13:43 UTC, Rxann commented
I did the first time, but it didn't seem to work. Formatting changes just commited!

2021-09-03 13:52 UTC, Dorukyum commented
The spacing still looks long.

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +    )
```suggestion
    await ctx.send(embed=embed)
    # This will send the mentioned user or the authors avatar in an embed!
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +    )
```suggestion
    member = member or ctx.author
    # If no one is passed in for the member argument, it will make the author the member.
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +):
```suggestion
async def avatar(ctx, member : discord.Member = None):
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +    embed = discord.Embed(title=f"{member}'s avatar",color = discord.Color.blurple())
```suggestion
    embed = discord.Embed(title=f"{member}'s avatar", color=discord.Color.blurple())
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +):
```suggestion
async def ephemeral(ctx, text : str):
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +    )
```suggestion
    await ctx.reply(content=text, ephemeral=True)
    # This will send the text back in an ephemeral message!
```

2021-09-03 13:59 UTC, MhmCats commented on examples/app_commands/slash_basic.py
> +    ''' Display a users avatar     '''
```suggestion
    ''' Display a users avatar '''
```

2021-09-03 15:15 UTC, Rxann commented
Thank you for all the suggestions! I am working on them now!

2021-09-03 15:20 UTC, Rxann commented
All of the suggested changes should be implemented now!

2021-09-03 16:24 UTC, Dorukyum requested changes

2021-09-03 16:24 UTC, Dorukyum commented on examples/app_commands/slash_basic.py
> +    embed = discord.Embed(title=f"{member}'s avatar",color=discord.Color.blurple())
```suggestion
    embed = discord.Embed(title=f"{member}'s avatar", color=discord.Color.blurple())
```

2021-09-03 16:24 UTC, Dorukyum commented on examples/app_commands/slash_basic.py
> +    ''' Display a users avatar'''
```suggestion
    '''Display a user's avatar'''
```

2021-09-03 16:24 UTC, Dorukyum commented on examples/app_commands/slash_basic.py
> +async def avatar(ctx,member : discord.Member = None):
```suggestion
async def avatar(ctx, member: discord.Member = None):
```

2021-09-03 16:24 UTC, Dorukyum commented on examples/app_commands/slash_basic.py
> +    # This will send the mentioned user or the authors avatar in an embed!
```suggestion
    # This will send the mentioned user or the author's avatar in an embed!
```

2021-09-03 16:24 UTC, Dorukyum commented on examples/app_commands/slash_basic.py
> +    '''Sends an empherial message, when a slash command is used!'''
```suggestion
    '''Sends an ephemeral message.'''
```

2021-09-03 18:21 UTC, Rxann commented
Thank you, changes just completed!

2021-09-04 03:45 UTC, CodeWithSwastik commented
Just so you know, you can use black to format 🤷

2021-09-04 12:44 UTC, Rxann commented
Yes, I use black for formatting!

2021-09-09 07:08 UTC, Grace-codes commented
This still has styling issues and you say you used black 🤦‍♀️

2021-09-10 03:19 UTC, nerdguyahmad commented on examples/app_commands/slash_basic.py
> +    '''Sends an empherial message.'''
```suggestion
    '''Sends an emphermal message.'''
```

2021-09-10 03:21 UTC, nerdguyahmad requested changes

2021-09-10 03:21 UTC, nerdguyahmad commented on examples/app_commands/slash_basic.py
> +async def avatar(ctx, member : discord.Member = None):
```suggestion
async def avatar(ctx, member: discord.Member = None):

```

2021-09-10 03:21 UTC, nerdguyahmad commented on examples/app_commands/slash_basic.py
> +    '''Sends an empherial message.'''
```suggestion
    '''Sends an emphermal message.'''
```

2021-09-10 03:21 UTC, nerdguyahmad commented on examples/app_commands/slash_basic.py
> +
Too many new lines.

2021-09-16 23:45 UTC, Middledot commented
I don't think this example is entirely necessary

2021-09-20 00:17 UTC, Rxann commented
Oki if you would like I can close it

2021-09-24 16:11 UTC, Dorukyum commented
Unfortunately this still has problems, and I dont think it's needed. Thanks for the pull request anyway.

2021-09-24 16:43 UTC, closed without merging