Trunk/docs
Pycord-Development/pycord pull request #775
Opened 2022-01-13 09:58 UTC by Lulalaby

2022-01-14 17:45 UTC, BobDotCom requested changes
I made some suggestions, but I haven't finished all the files yet

2022-01-14 17:53 UTC, Lulalaby commented on .gitignore
> +test.py
```suggestion
test.py
*.png
```

2022-01-20 10:19 UTC, VincentRPS commented on .gitignore
> -*.png
when i was uploading the newer images i had to remove png's from the ignore because the new images would've been ignored

2022-01-22 14:07 UTC, BruceCodesGithub submitted a review, later dismissed
Seems good, a lot of grammar fixed

2022-01-22 22:31 UTC, Middledot commented on examples/app_commands/info.py
> +            guilds=True,
What’s with the indents here?

2022-01-22 22:32 UTC, Lulalaby commented on examples/app_commands/info.py
> +            guilds=True,
idk

2022-01-23 02:38 UTC, Lulalaby commented on README.rst
> +- `Documentation <https://docs.pycord.dev/en/latest/index.html>`_
```suggestion
- `Documentation <https://docs.pycord.dev/en/master/index.html>`_
```

2022-01-23 02:41 UTC, Middledot submitted a review, later dismissed

2022-01-23 02:42 UTC, Lulalaby reviewed
LGTM for me

2022-01-23 02:47 UTC, VincentRPS approved these changes

2022-01-23 03:08 UTC, VincentRPS commented on discord/commands/core.py
> +class Option:
@Lulalaby something broke here

2022-01-23 03:10 UTC, Lulalaby commented on discord/commands/core.py
> +class Option:
Meh fix it

2022-01-23 03:26 UTC, VincentRPS approved these changes

2022-01-23 15:54 UTC, Middledot submitted a review, later dismissed

2022-01-24 15:33 UTC, Middledot approved these changes

2022-01-24 15:34 UTC, Dorukyum approved these changes

2022-01-24 15:34 UTC, merged